// frontend/App.tsx
import { useState, useEffect } from "react"
import { invoke } from "@tauri-apps/api/core"
import { listen } from "@tauri-apps/api/event"
import { getCurrentWindow } from "@tauri-apps/api/window"
import { Minus, Square, X, ChevronLeft, ChevronRight, Home, Package, Puzzle, Server, HatGlasses, Terminal, Settings, Camera, Download } from "lucide-react"
import { HomeTab } from "./features/home/HomeTab"
import { InstancesTab } from "./features/instances/InstancesTab"
import { BrowseTab } from "./features/browse/BrowseTab"
import { ConsoleTab } from "./features/console/ConsoleTab"
import { SettingsModal } from "./features/settings/SettingsModal"
import { ServersTab } from "./features/servers/ServersTab"
import { SkinsTab } from "./features/skins/SkinsTab"
import { CreateInstanceModal } from "./features/instances/CreateInstanceModal"
import { CreationProgressToast } from "./features/instances/CreationProgressToast"
import { UpdateDropdown } from "./features/instances/UpdateDropdown"
import { InstanceDetailsTab } from "./features/instances/InstanceDetailsTab"
import { ConfirmModal, AlertModal } from "./components/ui/ConfirmModal"
import { ScreenshotsTab } from "./features/screenshots/ScreenshotsTab"
import { Sidebar } from "./components/layout/Sidebar"
import type { Instance, LauncherSettings, ConsoleLog, AccountInfo, UpdateInfo } from "./types"

function App() {
  const [isReady, setIsReady] = useState(false)
  const [isAuthenticated, setIsAuthenticated] = useState(false)
  const [activeAccount, setActiveAccount] = useState<AccountInfo | null>(null)
  const [accounts, setAccounts] = useState<AccountInfo[]>([])
  const [launchingInstanceName, setLaunchingInstanceName] = useState<string | null>(null)
  const [runningInstances, setRunningInstances] = useState<Set<string>>(new Set())
  const [showCreateModal, setShowCreateModal] = useState(false)
  const [versions, setVersions] = useState<string[]>([])
  const [instances, setInstances] = useState<Instance[]>([])
  const [selectedInstance, setSelectedInstance] = useState<Instance | null>(null)
  const [launcherDirectory, setLauncherDirectory] = useState("")
  const [settings, setSettings] = useState<LauncherSettings | null>(null)
  const [activeTab, setActiveTab] = useState<"home" | "instances" | "browse" | "console" | "servers" | "skins" | "screenshots">("home")
  const [consoleLogs, setConsoleLogs] = useState<ConsoleLog[]>([])
  const [showInstanceDetails, setShowInstanceDetails] = useState(false)
  const [creatingInstanceName, setCreatingInstanceName] = useState<string | null>(null)
  const [confirmModal, setConfirmModal] = useState<{
    isOpen: boolean
    title: string
    message: string
    type: "warning" | "danger" | "success" | "info"
    onConfirm: () => void
  } | null>(null)
  const [alertModal, setAlertModal] = useState<{
    isOpen: boolean
    title: string
    message: string
    type: "warning" | "danger" | "success" | "info"
  } | null>(null)
  const [instanceIcons, setInstanceIcons] = useState<Record<string, string | null>>({})
  const [navigationHistory, setNavigationHistory] = useState<Array<{tab: typeof activeTab, showDetails: boolean, instance: Instance | null}>>([])
  const [historyIndex, setHistoryIndex] = useState(-1)
  const [isNavigating, setIsNavigating] = useState(false)
  const [sidebarBackground, setSidebarBackground] = useState<string | null>(null)
  const [showSettingsModal, setShowSettingsModal] = useState(false)
  const [sidebarContextMenu, setSidebarContextMenu] = useState<{
    x: number
    y: number
    instance: Instance
  } | null>(null)
  const [updateInfo, setUpdateInfo] = useState<UpdateInfo | null>(null)
  const [showUpdateDropdown, setShowUpdateDropdown] = useState(false)
  const [isInstallingUpdate, setIsInstallingUpdate] = useState(false)

  const appWindow = getCurrentWindow()

  const pushToHistory = (tab: typeof activeTab, showDetails: boolean, instance: Instance | null) => {
    if (isNavigating) return
    setNavigationHistory(prev => {
      const newHistory = prev.slice(0, historyIndex + 1)
      newHistory.push({ tab, showDetails, instance })
      return newHistory
    })
    setHistoryIndex(prev => prev + 1)
  }

  const navigateBack = () => {
    if (historyIndex > 0) {
      setIsNavigating(true)
      const newIndex = historyIndex - 1
      const state = navigationHistory[newIndex]
      setActiveTab(state.tab)
      setShowInstanceDetails(state.showDetails)
      if (state.instance) setSelectedInstance(state.instance)
      setHistoryIndex(newIndex)
      setTimeout(() => setIsNavigating(false), 0)
    }
  }

  const navigateForward = () => {
    if (historyIndex < navigationHistory.length - 1) {
      setIsNavigating(true)
      const newIndex = historyIndex + 1
      const state = navigationHistory[newIndex]
      setActiveTab(state.tab)
      setShowInstanceDetails(state.showDetails)
      if (state.instance) setSelectedInstance(state.instance)
      setHistoryIndex(newIndex)
      setTimeout(() => setIsNavigating(false), 0)
    }
  }

  const checkForUpdates = async () => {
    try {
      const update = await invoke<string | null>("check_for_updates")
      if (update) {
        const parts = update.split(' -> ')
        if (parts.length === 2) {
          const info: UpdateInfo = {
            current_version: parts[0].trim(),
            new_version: parts[1].trim()
          }
          const dismissedVersion = sessionStorage.getItem("dismissed_update_version")
          if (dismissedVersion !== info.new_version) {
            setUpdateInfo(info)
          }
        }
      }
    } catch (error) {
      console.error("Failed to check for updates:", error)
    }
  }

  const handleInstallUpdate = async () => {
    if (!updateInfo) return
    setIsInstallingUpdate(true)
    try {
      await invoke("install_update")
    } catch (error) {
      console.error("Failed to install update:", error)
      setAlertModal({
        isOpen: true,
        title: "Update Failed",
        message: `Failed to install update: ${error}`,
        type: "danger"
      })
      setIsInstallingUpdate(false)
      setShowUpdateDropdown(false)
    }
  }

  const tabs = [
    { id: "home" as const, icon: Home, label: "Home" },
    { id: "instances" as const, icon: Package, label: "Instances" },
    { id: "browse" as const, icon: Puzzle, label: "Addons" },
    { id: "servers" as const, icon: Server, label: "Servers" },
    { id: "skins" as const, icon: HatGlasses, label: "Skins" },
    { id: "screenshots" as const, icon: Camera, label: "Screenshots" },
    { id: "console" as const, icon: Terminal, label: "Console" },
  ]

  useEffect(() => {
    const initializeApp = async () => {
      await new Promise(resolve => setTimeout(resolve, 100))
      setIsReady(true)
      const splash = document.getElementById('splash-screen')
      const root = document.getElementById('root')
      if (splash && root) {
        splash.classList.add('hidden')
        root.classList.add('visible')
        setTimeout(() => splash.remove(), 500)
      }
      checkForUpdates()
    }
    initializeApp()
  }, [])

  useEffect(() => {
    if (!isReady) return
    loadVersions()
    loadInstances()
    loadLauncherDirectory()
    loadSettings()
    loadAccounts()
    loadSidebarBackground()
    
    const unlistenConsole = listen<ConsoleLog>("console-log", (event) => {
      setConsoleLogs((prev) => [...prev, event.payload])
    })

    const unlistenExit = listen<{ instance: string }>("instance-exited", (event) => {
      setRunningInstances((prev) => {
        const newSet = new Set(prev)
        newSet.delete(event.payload.instance)
        return newSet
      })
      setLaunchingInstanceName(null)
    })

    const unlistenServerLaunch = listen<{ instance: string, server: string }>("server-instance-launching", (event) => {
      setLaunchingInstanceName(event.payload.instance)
      setConsoleLogs([])
      if (settings?.auto_navigate_to_console !== false) setActiveTab("console")
      setRunningInstances((prev) => new Set(prev).add(event.payload.instance))
    })

    return () => {
      unlistenConsole.then((fn) => fn())
      unlistenExit.then((fn) => fn())
      unlistenServerLaunch.then((fn) => fn())
    }
  }, [isReady])

  useEffect(() => {
    if (!isNavigating && isReady) {
      pushToHistory(activeTab, showInstanceDetails, selectedInstance)
    }
  }, [activeTab, showInstanceDetails, selectedInstance?.name])

  useEffect(() => {
    const loadIcons = async () => {
      const icons: Record<string, string | null> = {}
      for (const instance of instances) {
        try {
          const icon = await invoke<string | null>("get_instance_icon", { instanceName: instance.name })
          icons[instance.name] = icon
        } catch {
          icons[instance.name] = null
        }
      }
      setInstanceIcons(icons)
    }
    if (instances.length > 0) loadIcons()
  }, [instances])

  useEffect(() => {
    const handleClickOutside = (e: MouseEvent) => {
      if (showUpdateDropdown) {
        const target = e.target as HTMLElement
        if (!target.closest('[data-update-dropdown]') && !target.closest('[data-update-button]')) {
          setShowUpdateDropdown(false)
        }
      }
    }

    document.addEventListener('mousedown', handleClickOutside)
    return () => document.removeEventListener('mousedown', handleClickOutside)
  }, [showUpdateDropdown])

  const loadVersions = async () => {
    try {
      const versionList = await invoke<string[]>("get_minecraft_versions")
      setVersions(versionList)
    } catch (error) {
      console.error("Failed to load versions:", error)
    }
  }

  const loadInstances = async () => {
    try {
      const instanceList = await invoke<Instance[]>("get_instances")
      setInstances(instanceList)
      if (selectedInstance) {
        const updated = instanceList.find(i => i.name === selectedInstance.name)
        if (updated) setSelectedInstance(updated)
        else setSelectedInstance(instanceList[0] || null)
      } else if (instanceList.length > 0 && !selectedInstance) {
        setSelectedInstance(instanceList[0])
      }
    } catch (error) {
      console.error("Failed to load instances:", error)
    }
  }

  const loadLauncherDirectory = async () => {
    try {
      const dir = await invoke<string>("get_launcher_directory")
      setLauncherDirectory(dir)
    } catch (error) {
      console.error("Failed to get launcher directory:", error)
    }
  }

  const loadSettings = async () => {
    try {
      const s = await invoke<LauncherSettings>("get_settings")
      setSettings(s)
    } catch (e) {
      console.error("Failed to load settings", e)
    }
  }

  const loadSidebarBackground = async () => {
    try {
      const bg = await invoke<string | null>("get_sidebar_background")
      setSidebarBackground(bg)
    } catch (error) {
      console.error("Failed to load sidebar background:", error)
    }
  }

  const loadAccounts = async () => {
    try {
      const accountList = await invoke<AccountInfo[]>("get_accounts")
      setAccounts(accountList)
      const active = accountList.find(acc => acc.is_active)
      setActiveAccount(active || null)
      setIsAuthenticated(!!active)
    } catch (error) {
      console.error("Failed to load accounts:", error)
    }
  }

  const handleLaunch = async (instance: Instance) => {
    if (!activeAccount) return
    setLaunchingInstanceName(instance.name)
    setConsoleLogs([])
    if (settings?.auto_navigate_to_console !== false) setActiveTab("console")
    setShowInstanceDetails(false)
    try {
      await invoke<string>("launch_instance_with_active_account", {
        instanceName: instance.name,
        appHandle: appWindow,
      })
      await loadInstances()
      setRunningInstances((prev) => new Set(prev).add(instance.name))
      setLaunchingInstanceName(null)
    } catch (error) {
      console.error("Launch error:", error)
      setLaunchingInstanceName(null)
    }
  }

  const handleDeleteInstance = async (instanceName: string) => {
    setConfirmModal({
      isOpen: true,
      title: "Delete Instance",
      message: `Are you sure you want to delete "${instanceName}"?\n\nThis action cannot be undone.`,
      type: "danger",
      onConfirm: async () => {
        try {
          await invoke<string>("delete_instance", { instanceName })
          await loadInstances()
          if (selectedInstance?.name === instanceName) {
            setSelectedInstance(instances.length > 1 ? instances.find(i => i.name !== instanceName) || null : null)
          }
          setConfirmModal(null)
        } catch (error) {
          console.error("Delete error:", error)
          setConfirmModal(null)
        }
      }
    })
  }

  const handleDuplicateInstance = async (instance: Instance) => {
    let baseName = instance.name
    let counter = 1
    let newName = `${baseName} (Copy)`
    while (instances.some(i => i.name === newName)) {
      counter++
      newName = `${baseName} (Copy ${counter})`
    }

    setCreatingInstanceName(newName)
    try {
      await invoke("duplicate_instance", {
        instanceName: instance.name,
        newName,
        appHandle: appWindow,
      })
      await loadInstances()
    } catch (error) {
      console.error("Duplicate error:", error)
      setCreatingInstanceName(null)
      setAlertModal({
        isOpen: true,
        title: "Error",
        message: `Failed to duplicate instance: ${error}`,
        type: "danger"
      })
    }
  }

  const handleOpenInstanceFolderByInstance = async (instance: Instance) => {
    try {
      await invoke("open_instance_folder", { instanceName: instance.name })
    } catch (error) {
      console.error("Failed to open folder:", error)
    }
  }

  const handleShowDetails = (instance: Instance) => {
    setSelectedInstance(instance)
    setShowInstanceDetails(true)
  }

  const handleCloseDetails = () => {
    setShowInstanceDetails(false)
  }

  const handleStartCreating = (instanceName: string) => {
    setCreatingInstanceName(instanceName)
    setActiveTab('instances')
  }

  const handleCreationComplete = () => {
    setCreatingInstanceName(null)
    loadInstances()
  }

  const handleCreationError = () => {
    setCreatingInstanceName(null)
  }

  const handleQuickLaunch = async (instance: Instance) => {
    if (!activeAccount) return
    setLaunchingInstanceName(instance.name)
    setConsoleLogs([])
    if (settings?.auto_navigate_to_console !== false) setActiveTab("console")
    try {
      await invoke<string>("launch_instance_with_active_account", {
        instanceName: instance.name,
        appHandle: appWindow,
      })
      await loadInstances()
      setRunningInstances((prev) => new Set(prev).add(instance.name))
      setLaunchingInstanceName(null)
    } catch (error) {
      console.error("Launch error:", error)
      setLaunchingInstanceName(null)
    }
  }

  const handleKillInstance = async (instance: Instance) => {
    try {
      await invoke("kill_instance", { instanceName: instance.name })
      setRunningInstances((prev) => {
        const newSet = new Set(prev)
        newSet.delete(instance.name)
        return newSet
      })
    } catch (error) {
      console.error("Failed to kill instance:", error)
      setAlertModal({
        isOpen: true,
        title: "Error",
        message: `Failed to stop instance: ${error}`,
        type: "danger"
      })
    }
  }

  return (
    <div className="flex flex-col h-screen bg-[#181a1f] text-[#e6e6e6] overflow-hidden font-sans">
      <div
        data-tauri-drag-region
        style={{ userSelect: 'none', WebkitAppRegion: 'drag' } as any}
        className="h-10 bg-[#22252b] flex-shrink-0 fixed top-0 left-0 right-0 z-50 flex items-center"
      >
        <div className="flex items-center gap-2 ml-4 mr-4">
          <img src="/logo.png" alt="Octane Launcher" className="h-5 w-5" />
          <span className="text-sm font-semibold text-[#e6e6e6]">Octane Launcher</span>
        </div>

        <div className="flex items-center gap-1 mr-4" style={{ WebkitAppRegion: 'no-drag' } as any}>
          <button
            onClick={navigateBack}
            disabled={historyIndex <= 0}
            className={`h-7 w-7 flex items-center justify-center rounded transition-colors ${
              historyIndex > 0 ? "text-[#e6e6e6] hover:bg-[#3a3f4b] cursor-pointer" : "text-[#3a3f4b] cursor-not-allowed"
            }`}
          >
            <ChevronLeft size={16} strokeWidth={4} />
          </button>
          <button
            onClick={navigateForward}
            disabled={historyIndex >= navigationHistory.length - 1}
            className={`h-7 w-7 flex items-center justify-center rounded transition-colors ${
              historyIndex < navigationHistory.length - 1 ? "text-[#e6e6e6] hover:bg-[#3a3f4b] cursor-pointer" : "text-[#3a3f4b] cursor-not-allowed"
            }`}
          >
            <ChevronRight size={16} strokeWidth={4} />
          </button>
        </div>

        <div className="flex-1 flex items-center justify-center" style={{ WebkitAppRegion: 'drag' } as any}>
          <nav className="flex items-center gap-1" style={{ WebkitAppRegion: 'no-drag' } as any}>
            {tabs.map((tab) => {
              const Icon = tab.icon
              return (
                <button
                  key={tab.id}
                  onClick={() => { setActiveTab(tab.id); setShowInstanceDetails(false) }}
                  className={`flex items-center gap-2 px-3 py-1.5 rounded text-sm font-medium transition-all cursor-pointer ${
                    activeTab === tab.id ? "bg-[#181a1f] text-[#e6e6e6]" : "text-[#7d8590] hover:text-[#e6e6e6] hover:bg-[#3a3f4b]"
                  }`}
                >
                  <Icon size={16} strokeWidth={1.5} />
                  <span>{tab.label}</span>
                </button>
              )
            })}
          </nav>
        </div>

        <div className="flex items-center ml-auto relative" style={{ WebkitAppRegion: 'no-drag' } as any}>
          {updateInfo && (
            <div className="relative">
              <button
                data-update-button
                onClick={() => setShowUpdateDropdown(!showUpdateDropdown)}
                className="flex items-center justify-center px-3 py-1.5 rounded text-[#16a34a] hover:text-[#15803d] hover:bg-[#3a3f4b] transition-all cursor-pointer"
                title={`Update available: ${updateInfo.new_version}`}
              >
                <Download size={16} strokeWidth={1.5} />
              </button>

              {showUpdateDropdown && (
                <UpdateDropdown
                  newVersion={updateInfo.new_version}
                  isInstalling={isInstallingUpdate}
                  onInstall={handleInstallUpdate}
                />
              )}
            </div>
          )}

          <button
            onClick={() => setShowSettingsModal(true)}
            className="flex items-center justify-center px-3 py-1.5 rounded text-[#7d8590] hover:text-[#e6e6e6] hover:bg-[#3a3f4b] transition-all cursor-pointer"
            title="Settings"
          >
            <Settings size={16} strokeWidth={1.5} />
          </button>
          <div className="w-px h-6 bg-[#3a3f4b] mx-2" style={{ pointerEvents: 'none' } as any} />
          <button onClick={() => appWindow.minimize()} className="h-10 w-12 flex items-center justify-center text-[#7d8590] hover:text-[#e6e6e6] hover:bg-[#3a3f4b] transition-colors">
            <Minus size={16} strokeWidth={1.5} />
          </button>
          <button onClick={() => appWindow.toggleMaximize()} className="h-10 w-12 flex items-center justify-center text-[#7d8590] hover:text-[#e6e6e6] hover:bg-[#3a3f4b] transition-colors">
            <Square size={14} strokeWidth={1.5} />
          </button>
          <button onClick={() => appWindow.close()} className="h-10 w-12 flex items-center justify-center text-[#7d8590] hover:text-[#e6e6e6] hover:bg-red-500 transition-colors">
            <X size={16} strokeWidth={1.5} />
          </button>
        </div>
      </div>

      {creatingInstanceName && (
        <CreationProgressToast
          instanceName={creatingInstanceName}
          onError={handleCreationError}
          onDismiss={() => setCreatingInstanceName(null)}
        />
      )}

      {confirmModal && (
        <ConfirmModal
          isOpen={confirmModal.isOpen}
          title={confirmModal.title}
          message={confirmModal.message}
          type={confirmModal.type}
          confirmText={confirmModal.type === "danger" ? "Delete" : "Confirm"}
          onConfirm={confirmModal.onConfirm}
          onCancel={() => setConfirmModal(null)}
        />
      )}

      {alertModal && (
        <AlertModal
          isOpen={alertModal.isOpen}
          title={alertModal.title}
          message={alertModal.message}
          type={alertModal.type}
          onClose={() => setAlertModal(null)}
        />
      )}

      <div className="flex flex-1 overflow-hidden mt-10">
        <Sidebar
          setActiveTab={setActiveTab}
          setShowInstanceDetails={setShowInstanceDetails}
          instances={instances}
          instanceIcons={instanceIcons}
          runningInstances={runningInstances}
          launchingInstanceName={launchingInstanceName}
          isAuthenticated={isAuthenticated}
          activeAccount={activeAccount}
          accounts={accounts}
          sidebarBackground={sidebarBackground}
          sidebarContextMenu={sidebarContextMenu}
          setSidebarContextMenu={setSidebarContextMenu}
          setSelectedInstance={setSelectedInstance}
          setShowSettingsModal={setShowSettingsModal}
          onQuickLaunch={handleQuickLaunch}
          onKillInstance={handleKillInstance}
          onOpenInstanceFolder={handleOpenInstanceFolderByInstance}
          onDuplicateInstance={handleDuplicateInstance}
          onDeleteInstance={handleDeleteInstance}
          loadAccounts={loadAccounts}
        />

        <main className="flex-1 overflow-y-auto bg-[#181a1f]">
          {showInstanceDetails && selectedInstance ? (
            <InstanceDetailsTab
              instance={selectedInstance}
              isAuthenticated={isAuthenticated}
              isLaunching={launchingInstanceName === selectedInstance.name}
              isRunning={runningInstances.has(selectedInstance.name)}
              onLaunch={() => handleLaunch(selectedInstance)}
              onBack={handleCloseDetails}
              onInstanceUpdated={loadInstances}
            />
          ) : (
            <>
              {activeTab === "home" && (
                <HomeTab
                  instances={instances}
                  isAuthenticated={isAuthenticated}
                  launchingInstanceName={launchingInstanceName}
                  runningInstances={runningInstances}
                  onLaunch={handleLaunch}
                  onDeleteInstance={handleDeleteInstance}
                  onCreateNew={() => setShowCreateModal(true)}
                  onShowDetails={handleShowDetails}
                  onOpenFolderByInstance={handleOpenInstanceFolderByInstance}
                  onDuplicateInstance={handleDuplicateInstance}
                  onKillInstance={handleKillInstance}
                />
              )}

              {activeTab === "instances" && (
                <InstancesTab
                  instances={instances}
                  isAuthenticated={isAuthenticated}
                  launchingInstanceName={launchingInstanceName}
                  runningInstances={runningInstances}
                  onSetSelectedInstance={setSelectedInstance}
                  onLaunch={(instance: Instance) => { handleLaunch(instance) }}
                  onCreateNew={() => setShowCreateModal(true)}
                  onShowDetails={handleShowDetails}
                  onOpenFolder={handleOpenInstanceFolderByInstance}
                  onDuplicateInstance={handleDuplicateInstance}
                  onDeleteInstance={handleDeleteInstance}
                  onKillInstance={handleKillInstance}
                />
              )}

              {activeTab === "browse" && (
                <BrowseTab
                  selectedInstance={selectedInstance}
                  instances={instances}
                  onSetSelectedInstance={setSelectedInstance}
                  onRefreshInstances={loadInstances}
                  onShowCreationToast={handleStartCreating}
                />
              )}

              {activeTab === "servers" && (
                <ServersTab
                  runningInstances={runningInstances}
                />
              )}

              {activeTab === "skins" && (
                <SkinsTab
                  activeAccount={activeAccount}
                  isAuthenticated={isAuthenticated}
                  invoke={invoke}
                />
              )}

              {activeTab === "screenshots" && <ScreenshotsTab />}
              {activeTab === "console" && (
                <ConsoleTab
                  consoleLogs={consoleLogs}
                  onClearConsole={(instanceName: string) => {
                    setConsoleLogs(prev => prev.filter(log => log.instance !== instanceName))
                  }}
                />
              )}
            </>
          )}
        </main>
      </div>

      <SettingsModal
        isOpen={showSettingsModal}
        settings={settings}
        launcherDirectory={launcherDirectory}
        onClose={() => setShowSettingsModal(false)}
        onSettingsChange={setSettings}
        onBackgroundChanged={loadSidebarBackground}
      />

      {showCreateModal && (
        <CreateInstanceModal
          versions={versions}
          instances={instances}
          onClose={() => setShowCreateModal(false)}
          onSuccess={handleCreationComplete}
          onStartCreating={handleStartCreating}
        />
      )}
    </div>
  )
}

export default App

// frontend/App.svelte
<script lang="ts">
  import TitleBar from "./components/layout/TitleBar.svelte"
  import Sidebar from "./components/layout/Sidebar.svelte"
  import FriendsPanel from "./features/social/FriendsPanel.svelte"
  import SettingsModal from "./features/settings/SettingsModal.svelte"
  import CreateInstanceModal from "./features/instances/CreateInstanceModal.svelte"
  import CreationProgressToast from "./features/instances/CreationProgressToast.svelte"
  import InstanceDetailsTab from "./features/instances/InstanceDetailsTab.svelte"
  import ConfirmModal from "./components/ui/ConfirmModal.svelte"
  import AlertModal from "./components/ui/AlertModal.svelte"
  import ExportModal from "./features/instances/ExportModal.svelte"
  import OnboardingModal from "./features/onboarding/OnboardingModal.svelte"
  import GlobalSearch from "./components/ui/GlobalSearch.svelte"
  import Toaster from "./components/ui/Toaster.svelte"
  import HomeTab from "./features/home/HomeTab.svelte"
  import InstancesTab from "./features/instances/InstancesTab.svelte"
  import AddonsTab from "./features/addons/AddonsTab.svelte"
  import ConsoleTab from "./features/console/ConsoleTab.svelte"
  import ServersTab from "./features/servers/ServersTab.svelte"
  import SkinsTab from "./features/skins/SkinsTab.svelte"
  import ScreenshotsTab from "./features/screenshots/ScreenshotsTab.svelte"
  import ContextMenu from "./components/ui/ContextMenu.svelte"
  import {
    store,
    setShowSettingsModal, setShowCreateModal, setConfirmModal,
    setAlertModal, loadAllInitialData, setupEventListeners, pushToHistory,
    handleStartCreating, handleCreationComplete, handleCreationError,
    setExportModal, setShowSearchPalette, navigateBack, navigateForward,
  } from "./lib/launcherStore.svelte"
  import { onMount, untrack } from "svelte"
  import { invoke } from "@tauri-apps/api/core"
  import { ArrowLeft, ArrowRight, RefreshCw, Search } from "lucide-svelte"

  const SPLASH_DELAY_MS = 100
  const SPLASH_REMOVE_MS = 500

  const tabs = {
    home: HomeTab,
    instances: InstancesTab,
    addons: AddonsTab,
    servers: ServersTab,
    skins: SkinsTab,
    screenshots: ScreenshotsTab,
    console: ConsoleTab,
  }

  let globalMenu = $state<{ x: number; y: number } | null>(null)

  const ActiveTab = $derived(tabs[store.activeTab as keyof typeof tabs])

  const backgroundStyle = $derived(
    store.background
      ? `background-image: url("${store.background}"); background-size: cover; background-position: center`
      : "background-color: var(--content-bg)"
  )

  const overlayStyle = $derived.by(() => {
    const darkness = ((store.settings?.background_darkness ?? 80) / 100).toFixed(2)
    const blur = store.settings?.background_blur ?? 0
    return `background: rgba(0,0,0,${darkness});${blur > 0 ? ` backdrop-filter: blur(${blur}px);` : ""}`
  })

  function handleGlobalKeydown(e: KeyboardEvent) {
    const key = e.key.toLowerCase()
    if ((e.ctrlKey || e.metaKey) && !e.shiftKey && !e.altKey && key === "f") {
      e.preventDefault()
      setShowSearchPalette(!store.showSearchPalette)
    }
  }

  function handleGlobalContextMenu(e: MouseEvent) {
    if (e.defaultPrevented) return
    const el = e.target as HTMLElement | null
    if (el?.closest("input, textarea, [contenteditable='true']")) return
    if (window.getSelection()?.toString()) return
    e.preventDefault()
    globalMenu = { x: e.clientX, y: e.clientY }
  }

  function dismissCreationToast() {
    store.creatingInstanceName = null
  }

  $effect(() => {
    if (!store.settings) return
    const theme = store.settings.theme || "octane"
    try { localStorage.setItem("octane_theme", theme) } catch {}
    const root = document.documentElement
    for (const cls of Array.from(root.classList)) {
      if (cls.startsWith("theme-")) root.classList.remove(cls)
    }
    root.classList.add(`theme-${theme}`)
  })

  onMount(() => {
    invoke("show_window").catch(() => {})
    setTimeout(() => {
      store.isReady = true
      const splash = document.getElementById("splash-screen")
      const root = document.getElementById("root")
      if (splash && root) {
        splash.classList.add("hidden")
        root.classList.add("visible")
        setTimeout(() => splash.remove(), SPLASH_REMOVE_MS)
      }
      loadAllInitialData()
    }, SPLASH_DELAY_MS)
  })

  $effect(() => {
    if (!store.isReady) return
    const cleanup: unknown = setupEventListeners()
    return () => {
      Promise.resolve(cleanup).then((fn) => {
        if (typeof fn === "function") fn()
      })
    }
  })

  $effect(() => {
    if (!store.isReady) return
    store.activeTab
    store.showInstanceDetails
    store.selectedInstance?.name
    untrack(pushToHistory)
  })
</script>

<svelte:window onkeydown={handleGlobalKeydown} oncontextmenu={handleGlobalContextMenu} />

<!-- preload avatar keeps the browser decode cache warm across tab switches -->
{#if store.activeAccount}
  <img src="https://renders.stellarmc.gg/bust/{store.activeAccount.username}" alt="" aria-hidden="true" class="fixed opacity-0 pointer-events-none" />
{/if}

{#if store.settings?.cat_mode}
  <img src="/cat.webp" alt="" aria-hidden="true" class="fixed top-0 left-1/2 -translate-x-1/2 z-40 h-12 w-auto pointer-events-none select-none" />
{/if}

<div class="flex flex-col h-screen bg-[var(--bg-primary)] text-[var(--text-primary)] overflow-hidden font-sans">
  <TitleBar />

  <div class="flex flex-1 overflow-hidden px-4 pb-4 gap-4">
    <Sidebar />

    <div class="flex-1 rounded-xl overflow-hidden flex flex-col relative" style={backgroundStyle}>
      {#if store.background}
        <div class="absolute inset-0" style={overlayStyle}></div>
      {/if}

      <main class="flex-1 min-h-0 overflow-y-auto relative">
        {#if store.showInstanceDetails && store.selectedInstance}
          <InstanceDetailsTab instance={store.selectedInstance} />
        {:else if ActiveTab}
          <ActiveTab />
        {/if}
      </main>

      {#if store.creatingInstanceName}
        <div class="absolute bottom-0 left-0 right-0 z-20">
          <CreationProgressToast
            instanceName={store.creatingInstanceName}
            onDismiss={dismissCreationToast}
            onError={handleCreationError}
          />
        </div>
      {/if}
    </div>

    <FriendsPanel
      isOpen={store.showFriendsPanel}
      isAuthenticated={store.isAuthenticated}
      activeAccountUuid={store.activeAccount?.uuid}
    />
  </div>

  {#if store.confirmModal}
    <ConfirmModal
      isOpen={store.confirmModal.isOpen}
      title={store.confirmModal.title}
      message={store.confirmModal.message}
      type={store.confirmModal.type}
      confirmText={store.confirmModal.type === "danger" ? "Delete" : "Confirm"}
      onConfirm={store.confirmModal.onConfirm}
      onCancel={() => setConfirmModal(null)}
      checkboxLabel={store.confirmModal.checkboxLabel}
      checkboxChecked={store.confirmModal.checkboxChecked}
      onCheckboxChange={store.confirmModal.onCheckboxChange}
    />
  {/if}

  {#if store.alertModal}
    <AlertModal
      isOpen={store.alertModal.isOpen}
      title={store.alertModal.title}
      message={store.alertModal.message}
      type={store.alertModal.type}
      onClose={() => setAlertModal(null)}
    />
  {/if}

  {#if store.exportModalInstance}
    <ExportModal
      instanceName={store.exportModalInstance.name}
      onClose={() => setExportModal(null)}
    />
  {/if}

  <SettingsModal
    isOpen={store.showSettingsModal}
    onClose={() => setShowSettingsModal(false)}
  />

  {#if store.showCreateModal}
    <CreateInstanceModal
      instances={store.instances}
      onClose={() => setShowCreateModal(false)}
      onSuccess={handleCreationComplete}
      onStartCreating={handleStartCreating}
    />
  {/if}

  {#if store.showOnboarding}
    <OnboardingModal />
  {/if}

  <GlobalSearch />

  {#if globalMenu}
    {@const gm = globalMenu}
    <ContextMenu
      x={gm.x}
      y={gm.y}
      onClose={() => (globalMenu = null)}
      items={[
        ...(store.historyIndex > 0 ? [{ label: "Back", icon: ArrowLeft, onClick: navigateBack }] : []),
        ...(store.historyIndex < store.navigationHistory.length - 1 ? [{ label: "Forward", icon: ArrowRight, onClick: navigateForward }] : []),
        { label: "Reload", icon: RefreshCw, onClick: () => window.location.reload() },
        { separator: true },
        { label: "Search", icon: Search, onClick: () => setShowSearchPalette(true) },
      ]}
    />
  {/if}

  <Toaster />
</div>
