// src/frontend/modals/ContextMenu.tsx
import { useEffect, useRef } from "react"

interface ContextMenuItem {
  label?: string
  icon?: React.ReactNode
  onClick?: () => void
  danger?: boolean
  separator?: boolean
}

interface ContextMenuProps {
  x: number
  y: number
  items: ContextMenuItem[]
  onClose: () => void
}

export function ContextMenu({ x, y, items, onClose }: ContextMenuProps) {
  const menuRef = useRef<HTMLDivElement>(null)

  useEffect(() => {
    const handleClickOutside = (e: MouseEvent) => {
      if (menuRef.current && !menuRef.current.contains(e.target as Node)) {
        onClose()
      }
    }

    const handleEscape = (e: KeyboardEvent) => {
      if (e.key === "Escape") {
        onClose()
      }
    }

    document.addEventListener("mousedown", handleClickOutside)
    document.addEventListener("keydown", handleEscape)

    return () => {
      document.removeEventListener("mousedown", handleClickOutside)
      document.removeEventListener("keydown", handleEscape)
    }
  }, [onClose])

  // Adjust position to keep menu on screen
  useEffect(() => {
    if (menuRef.current) {
      const rect = menuRef.current.getBoundingClientRect()
      const viewportWidth = window.innerWidth
      const viewportHeight = window.innerHeight

      let adjustedX = x
      let adjustedY = y

      if (rect.right > viewportWidth) {
        adjustedX = viewportWidth - rect.width - 8
      }

      if (rect.bottom > viewportHeight) {
        adjustedY = viewportHeight - rect.height - 8
      }

      menuRef.current.style.left = `${adjustedX}px`
      menuRef.current.style.top = `${adjustedY}px`
    }
  }, [x, y])

  return (
    <div
      ref={menuRef}
      className="fixed z-[100] bg-[#1a1a1a] border border-[#2a2a2a] rounded-lg overflow-hidden min-w-[180px]"
      style={{ left: x, top: y }}
    >
      {items.map((item, index) => (
        item.separator ? (
          <div key={index} className="h-px bg-[#2a2a2a] my-1 mx-2" />
        ) : (
          <button
            key={index}
            onClick={() => {
              if (item.onClick) {
                item.onClick()
              }
              onClose()
            }}
            className={`w-full flex items-center gap-3 px-3 py-2.5 text-sm transition-colors cursor-pointer ${
              item.danger
                ? "text-[#dc2626] hover:bg-[#dc2626]/10"
                : "text-[#e8e8e8] hover:bg-[#2a2a2a]"
            }`}
          >
            {item.icon && <span className="flex-shrink-0">{item.icon}</span>}
            <span>{item.label}</span>
          </button>
        )
      ))}
    </div>
  )
}

// frontend/components/ui/ContextMenu.svelte
<script lang="ts">
  import { portal } from "../../lib/portal"
  interface ContextMenuItem {
    label?: string
    icon?: new (...args: any[]) => any
    onClick?: () => void
    danger?: boolean
    separator?: boolean
  }

  let { x, y, items, onClose }: {
    x: number
    y: number
    items: ContextMenuItem[]
    onClose: () => void
  } = $props()

  let menuEl: HTMLDivElement | undefined = $state()
  let position = $state({ x: 0, y: 0 })

  $effect(() => {
    const close = onClose
    function handleClick(e: MouseEvent) {
      if (menuEl && !menuEl.contains(e.target as Node)) close()
    }
    function handleKey(e: KeyboardEvent) {
      if (e.key === 'Escape') close()
    }

    document.addEventListener("mousedown", handleClick)
    document.addEventListener("keydown", handleKey)
    return () => {
      document.removeEventListener("mousedown", handleClick)
      document.removeEventListener("keydown", handleKey)
    }
  })

  $effect(() => {
    if (!menuEl) {
      position = { x, y }
      return
    }
    const { width, height } = menuEl.getBoundingClientRect()
    const vw = window.innerWidth
    const vh = window.innerHeight
    position = {
      x: x + width > vw ? vw - width - 8 : x,
      y: y + height > vh ? vh - height - 8 : y,
    }
  })
</script>

<div use:portal>
  <div
    bind:this={menuEl}
    role="menu"
    class="fixed z-[100] bg-[var(--bg-secondary)] rounded-md overflow-hidden min-w-[180px] border border-[var(--border-subtle)]"
    style="left: {position.x}px; top: {position.y}px"
  >
    {#each items as item}
      {#if item.separator}
        <div class="h-px bg-[var(--bg-tertiary)] my-1 mx-2"></div>
      {:else}
        <button
          onclick={() => { item.onClick?.(); onClose() }}
          class="w-full flex items-center gap-3 px-3 py-2.5 text-sm transition-colors cursor-pointer {item.danger ? 'text-red-400 hover:bg-red-500/10' : 'text-[var(--text-primary)] hover:bg-[var(--bg-hover-strong)]'}"
        >
          {#if item.icon}
            <span class="flex-shrink-0">
              <item.icon size={16} />
            </span>
          {/if}
          <span>{item.label}</span>
        </button>
      {/if}
    {/each}
  </div>
</div>
