// src/frontend/tabs/ServersTab.tsx
import { Server, Plus, Search, Trash2, Play, MoreHorizontal } from "lucide-react"
import { useState, useEffect } from "react"
import { invoke } from "@tauri-apps/api/core"
import { useTranslation } from "react-i18next"
import { CreateServerModal } from "../modals/CreateServerModal"
import { ConfirmModal } from "../modals/ConfirmModal"
import type { ServerInfo, McSrvStatResponse } from "../../types"

interface ServersTabProps {
  launchingInstanceName: string | null
  runningInstances: Set<string>
}

export function ServersTab({ runningInstances }: ServersTabProps) {
  const { t } = useTranslation()
  const [servers, setServers] = useState<ServerInfo[]>([])
  const [searchQuery, setSearchQuery] = useState("")
  const [selectedServer, setSelectedServer] = useState<ServerInfo | null>(null)
  const [showAddModal, setShowAddModal] = useState(false)
  const [serverToDelete, setServerToDelete] = useState<string | null>(null)
  const [launchingServer, setLaunchingServer] = useState<string | null>(null)
  const isAnyInstanceRunning = runningInstances.size > 0

  useEffect(() => {
    loadServers()
  }, [])

  useEffect(() => {
    const interval = setInterval(() => {
      servers.forEach(server => {
        refreshServerStatus(server)
      })
    }, 5 * 60 * 1000)

    return () => clearInterval(interval)
  }, [servers])

  const loadServers = async () => {
    try {
      const serverList = await invoke<ServerInfo[]>("get_servers")
      setServers(serverList)
      serverList.forEach(server => {
        refreshServerStatus(server)
      })
    } catch (error) {
      console.error("Failed to load servers:", error)
      setServers([])
    }
  }

  const fetchServerStatus = async (address: string, port: number): Promise<ServerInfo | null> => {
    try {
      const fullAddress = port === 25565 ? address : `${address}:${port}`
      const response = await fetch(`https://api.mcsrvstat.us/3/${fullAddress}`, {
        headers: { 'User-Agent': 'OctaneLauncher/1.0' }
      })

      if (!response.ok) throw new Error(`API returned ${response.status}`)

      const data: McSrvStatResponse = await response.json()

      return {
        name: address,
        address,
        port,
        status: data.online ? "online" : "offline",
        players_online: data.players?.online,
        players_max: data.players?.max,
        players_list: data.players?.list,
        version: data.version || data.protocol?.name,
        motd: data.motd?.clean?.join('\n'),
        favicon: data.icon ? `https://api.mcsrvstat.us/icon/${fullAddress}` : undefined,
        last_checked: Date.now()
      }
    } catch (error) {
      console.error("Failed to fetch server status:", error)
      return null
    }
  }

  const refreshServerStatus = async (server: ServerInfo) => {
    try {
      const statusData = await fetchServerStatus(server.address, server.port)

      if (statusData) {
        setServers(prev => prev.map(s =>
          s.name === server.name ? { ...statusData, name: server.name } : s
        ))

        if (selectedServer?.name === server.name) {
          setSelectedServer({ ...statusData, name: server.name })
        }

        try {
          await invoke("update_server_status", { serverName: server.name, status: statusData })
        } catch (error) {
          console.error("Failed to save server status:", error)
        }
      }
    } catch (error) {
      console.error("Failed to refresh server:", error)
    }
  }

  const handleDeleteServer = async () => {
    if (!serverToDelete) return
    try {
      await invoke("delete_server", { serverName: serverToDelete })
      await loadServers()
      if (selectedServer?.name === serverToDelete) setSelectedServer(null)
    } catch (error) {
      console.error("Delete error:", error)
    } finally {
      setServerToDelete(null)
    }
  }

  const handleServerAdded = async (newServer: ServerInfo) => {
    try {
      await invoke("add_server", { name: newServer.name, address: newServer.address, port: newServer.port })
    } catch (error) {
      console.error("Failed to save server:", error)
      alert(`Failed to add server: ${error}`)
      return
    }

    const statusData = await fetchServerStatus(newServer.address, newServer.port)

    if (statusData) {
      const serverWithStatus = { ...statusData, name: newServer.name }
      setServers(prev => [...prev, serverWithStatus])
      try {
        await invoke("update_server_status", { serverName: newServer.name, status: statusData })
      } catch (error) {
        console.error("Failed to save server status:", error)
      }
    } else {
      setServers(prev => [...prev, { ...newServer, status: "unknown" }])
    }
  }

  const handleLaunchServer = async (server: ServerInfo, e: React.MouseEvent) => {
    e.stopPropagation()
    if (server.status !== "online") {
      alert(t('servers.errors.serverNotOnline'))
      return
    }
    setLaunchingServer(server.name)
    try {
      await invoke("launch_server", { serverAddress: server.address, serverPort: server.port, serverName: server.name })
      setTimeout(() => setLaunchingServer(null), 1000)
    } catch (error) {
      console.error("Failed to launch server:", error)
      alert(`${t('servers.errors.launchFailed')}: ${error}`)
      setLaunchingServer(null)
    }
  }

  const filteredServers = servers.filter(server =>
    server.name.toLowerCase().includes(searchQuery.toLowerCase()) ||
    server.address.toLowerCase().includes(searchQuery.toLowerCase())
  )

  const getStatusColor = (status: string) => {
    switch (status) {
      case "online": return "text-[#16a34a]"
      case "offline": return "text-[#dc2626]"
      default: return "text-[#7d8590]"
    }
  }

  const getStatusBgColor = (status: string) => {
    switch (status) {
      case "online": return "bg-[#16a34a]/10"
      case "offline": return "bg-[#dc2626]/10"
      default: return "bg-[#7d8590]/10"
    }
  }

  const getStatusText = (status: string) => {
    switch (status) {
      case "online": return t('servers.status.online')
      case "offline": return t('servers.status.offline')
      default: return t('servers.status.unknown')
    }
  }

  return (
    <>
      <style>{`
        .blur-border { position: relative; }
        .blur-border::before {
          content: '';
          position: absolute;
          inset: 0;
          border-radius: inherit;
          padding: 2px;
          background: linear-gradient(180deg, rgba(255,255,255,0.08), rgba(255,255,255,0.04));
          -webkit-mask: linear-gradient(#fff 0 0) content-box, linear-gradient(#fff 0 0);
          -webkit-mask-composite: xor;
          mask-composite: exclude;
          pointer-events: none;
          backdrop-filter: blur(8px);
          z-index: 10;
        }
        .blur-border:hover::before {
          background: linear-gradient(180deg, rgba(255,255,255,0.14), rgba(255,255,255,0.08));
        }
        .blur-border-input::before {
          content: '';
          position: absolute;
          inset: 0;
          border-radius: inherit;
          padding: 2px;
          background: linear-gradient(180deg, rgba(255,255,255,0.08), rgba(255,255,255,0.04));
          -webkit-mask: linear-gradient(#fff 0 0) content-box, linear-gradient(#fff 0 0);
          -webkit-mask-composite: xor;
          mask-composite: exclude;
          pointer-events: none;
          backdrop-filter: blur(8px);
          z-index: 10;
        }
        .blur-border-input:focus-within::before {
          background: linear-gradient(180deg, rgba(255,255,255,0.14), rgba(255,255,255,0.08));
        }
      `}</style>
      <div className="p-6 space-y-4">
        <div className="max-w-7xl mx-auto">
          <div className="flex items-center justify-between mb-4">
            <div>
              <h1 className="text-2xl font-semibold text-[#e6e6e6] tracking-tight">{t('servers.title')}</h1>
              <p className="text-sm text-[#7d8590] mt-0.5">{t('servers.subtitle')}</p>
            </div>
            <div className="flex items-center gap-2">
              {servers.length > 0 && (
                <div className="relative blur-border-input rounded-md bg-[#22252b]">
                  <Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-[#7d8590] z-20 pointer-events-none" strokeWidth={2} />
                  <input
                    type="text"
                    placeholder={t('servers.searchPlaceholder')}
                    value={searchQuery}
                    onChange={(e) => setSearchQuery(e.target.value)}
                    className="w-56 bg-transparent rounded-md pl-9 pr-3 py-1.5 text-sm text-[#e6e6e6] placeholder-[#7d8590] focus:outline-none transition-all relative z-10"
                  />
                </div>
              )}
              <button
                onClick={() => setShowAddModal(true)}
                className="px-4 h-8 bg-[#4572e3] hover:bg-[#3461d1] text-white rounded-md text-sm font-medium flex items-center gap-2 transition-colors cursor-pointer"
              >
                <Plus size={16} />
                {t('servers.addButton')}
              </button>
            </div>
          </div>

          {servers.length === 0 ? (
            <div className="flex flex-col items-center justify-center py-14">
              <Server size={48} className="text-[#7d8590] mb-3" strokeWidth={1.5} />
              <h3 className="text-base font-semibold text-[#e6e6e6] mb-1">{t('servers.noServers.title')}</h3>
              <p className="text-sm text-[#7d8590] mb-4">{t('servers.noServers.description')}</p>
              <button
                onClick={() => setShowAddModal(true)}
                className="px-4 py-2 bg-[#4572e3] hover:bg-[#3461d1] text-white rounded font-medium text-sm flex items-center gap-2 transition-all cursor-pointer"
              >
                <Plus size={16} strokeWidth={2} />
                <span>{t('servers.noServers.addButton')}</span>
              </button>
            </div>
          ) : filteredServers.length === 0 ? (
            <div className="rounded-md p-8 flex flex-col items-center justify-center">
              <Search size={48} className="text-[#e6e6e6] mb-3" strokeWidth={1.5} />
              <h3 className="text-base font-semibold text-[#e6e6e6] mb-1">{t('servers.noSearchResults.title')}</h3>
              <p className="text-sm text-[#7d8590]">{t('servers.noSearchResults.description')}</p>
            </div>
          ) : (
            <div className="grid grid-cols-1 lg:grid-cols-2 xl:grid-cols-3 gap-3">
              {filteredServers.map((server) => {
                const displayAddress = server.port === 25565 ? server.address : `${server.address}:${server.port}`
                const isLaunching = launchingServer === server.name

                return (
                  <div
                    key={server.name}
                    onClick={() => setSelectedServer(server)}
                    className="blur-border group bg-[#22252b] rounded-md p-4 cursor-pointer transition-all relative"
                  >
                    <button
                      onClick={(e) => { e.stopPropagation(); setServerToDelete(server.name) }}
                      className="absolute top-4 right-4 px-3 py-2 bg-[#dc2626]/10 hover:bg-[#dc2626]/20 text-[#dc2626] rounded text-xs font-medium transition-all cursor-pointer z-20"
                      title={t('servers.removeTooltip')}
                    >
                      <Trash2 size={14} />
                    </button>

                    <div className="flex gap-3 mb-2 pr-10 relative z-0">
                      {server.favicon ? (
                        <img src={server.favicon} alt={server.name} className="w-16 h-16 rounded object-cover" />
                      ) : (
                        <div className="w-16 h-16 bg-[#181a1f] rounded flex items-center justify-center flex-shrink-0">
                          <Server size={28} className="text-[#3a3f4b]" strokeWidth={1.5} />
                        </div>
                      )}
                      <div className="flex-1 min-w-0">
                        <h3 className="font-semibold text-base text-[#e6e6e6] truncate mb-0">{server.name}</h3>
                        <div className="flex items-center gap-2 mb-1">
                          <span className="text-xs text-[#7d8590] truncate">{displayAddress}</span>
                        </div>
                        <div className="flex items-center gap-2">
                          <span className={`px-2 py-0.5 rounded text-xs font-medium ${getStatusBgColor(server.status)} ${getStatusColor(server.status)}`}>
                            {getStatusText(server.status)}
                          </span>
                          {server.version && (
                            <span className="text-xs text-[#7d8590] truncate">{server.version}</span>
                          )}
                        </div>
                      </div>
                    </div>

                    {server.motd && (
                      <p className="text-xs text-[#7d8590] mb-2 truncate leading-relaxed relative z-0">{server.motd}</p>
                    )}

                    {server.status === "online" && server.players_online !== undefined && (
                      <div className="flex items-center justify-between mb-3">
                        <span className="text-sm font-medium text-[#e6e6e6]">{t('servers.players')}</span>
                        <div className="flex items-center gap-3">
                          {server.players_list && server.players_list.length > 0 && (
                            <div className="flex items-center gap-1.5">
                              <div className="flex items-center -space-x-1.5">
                                {server.players_list.slice(0, 5).map((player, index) => (
                                  <img
                                    key={player.uuid}
                                    src={`https://minotar.net/helm/${player.name}/32`}
                                    alt={player.name}
                                    title={player.name}
                                    className="w-5 h-5 rounded border-2 border-[#22252b] relative"
                                    style={{ zIndex: 5 - index }}
                                  />
                                ))}
                              </div>
                              {server.players_list.length > 5 && (
                                <button
                                  onClick={(e) => e.stopPropagation()}
                                  className="flex items-center justify-center w-5 h-5 rounded hover:bg-[#3a3f4b] transition-colors cursor-pointer"
                                  title={`${server.players_list.length - 5} more players`}
                                >
                                  <MoreHorizontal size={12} className="text-[#7d8590] hover:text-[#e6e6e6]" strokeWidth={2.5} />
                                </button>
                              )}
                            </div>
                          )}
                          <span className="text-sm font-medium text-[#e6e6e6]">
                            {server.players_online.toLocaleString()} / {server.players_max?.toLocaleString()}
                          </span>
                        </div>
                      </div>
                    )}

                    <button
                      onClick={(e) => handleLaunchServer(server, e)}
                      disabled={server.status !== "online" || isLaunching || isAnyInstanceRunning}
                      className={`w-full py-2.5 rounded font-medium text-sm flex items-center justify-center gap-2 transition-all relative z-20 ${
                        isAnyInstanceRunning || isLaunching
                          ? "bg-red-500/10 text-red-400 cursor-not-allowed"
                          : server.status === "online"
                          ? "bg-[#16a34a]/10 hover:bg-[#16a34a]/20 text-[#16a34a] cursor-pointer"
                          : "bg-[#3a3f4b] text-[#7d8590] cursor-not-allowed"
                      }`}
                    >
                      {isAnyInstanceRunning || isLaunching ? (
                        <div className="w-4 h-4 border-2 border-red-400/30 border-t-red-400 rounded-full animate-spin" />
                      ) : (
                        <Play size={16} fill="currentColor" strokeWidth={0} />
                      )}
                      <span>
                        {isAnyInstanceRunning ? t('servers.instanceRunning') : isLaunching ? t('servers.launching') : t('servers.play')}
                      </span>
                    </button>
                  </div>
                )
              })}
            </div>
          )}
        </div>

        {showAddModal && (
          <CreateServerModal
            servers={servers}
            onClose={() => setShowAddModal(false)}
            onSuccess={handleServerAdded}
          />
        )}

        <ConfirmModal
          isOpen={serverToDelete !== null}
          title={t('servers.confirmRemove.title')}
          message={t('servers.confirmRemove.message', { name: serverToDelete })}
          confirmText={t('servers.confirmRemove.confirm')}
          cancelText={t('common.actions.cancel')}
          type="danger"
          onConfirm={handleDeleteServer}
          onCancel={() => setServerToDelete(null)}
        />
      </div>
    </>
  )
}

// frontend/features/servers/ServersTab.svelte
<script lang="ts">
  import { Server, Plus, Search, Trash2, Play, GripVertical } from "lucide-svelte"
  import { invoke } from "@tauri-apps/api/core"
  import CreateServerModal from "./CreateServerModal.svelte"
  import ConfirmModal from "../../components/ui/ConfirmModal.svelte"
  import type { ServerInfo, McSrvStatResponse } from "../../types"
  import { store } from "../../lib/launcherStore.svelte"

  let servers: ServerInfo[] = $state([])
  let searchQuery = $state("")
  let showAddModal = $state(false)
  let serverToDelete = $state<string | null>(null)
  let launchingServer = $state<string | null>(null)
  let isAnyInstanceRunning = $derived(store.runningInstances.size > 0)

  $effect(() => { loadServers() })

  $effect(() => {
    const hasServers = servers.length > 0
    if (!hasServers) return
    const interval = setInterval(() => {
      servers.forEach(server => refreshServerStatus(server))
    }, 5 * 60 * 1000)
    return () => clearInterval(interval)
  })

  async function loadServers() {
    try {
      const serverList = await invoke<ServerInfo[]>("get_servers")
      servers = serverList
      serverList.forEach(server => refreshServerStatus(server))
    } catch (error) {
      console.error("Failed to load servers:", error)
      servers = []
    }
  }

  async function fetchServerStatus(address: string, port: number): Promise<ServerInfo | null> {
    try {
      const fullAddress = port === 25565 ? address : `${address}:${port}`
      const response = await fetch(`https://api.mcsrvstat.us/3/${fullAddress}`, {
        headers: { "User-Agent": "OctaneLauncher/1.0" },
      })

      if (!response.ok) throw new Error(`API returned ${response.status}`)

      const data: McSrvStatResponse = await response.json()

      let ping: number | undefined = undefined
      if (data.online) {
        try {
          ping = await invoke<number>("ping_server", { address, port })
        } catch (e) {
          console.error("Failed to ping server:", e)
        }
      }

      return {
        name: address,
        address,
        port,
        status: data.online ? "online" : "offline",
        players_online: data.players?.online,
        players_max: data.players?.max,
        players_list: data.players?.list,
        version: data.version || data.protocol?.name,
        motd: data.motd?.clean?.join("\n"),
        motd_html: data.motd?.html,
        favicon: data.icon ? `https://api.mcsrvstat.us/icon/${fullAddress}` : undefined,
        last_checked: Date.now(),
        ping,
      }
    } catch (error) {
      console.error("Failed to fetch server status:", error)
      return null
    }
  }

  async function refreshServerStatus(server: ServerInfo) {
    try {
      const statusData = await fetchServerStatus(server.address, server.port)
      if (statusData) {
        const updated = { ...statusData, name: server.name }
        servers = servers.map(s => s.name === server.name ? updated : s)
        try {
          await invoke("update_server_status", { serverName: server.name, status: statusData })
        } catch (e) { console.error("Failed to save server status:", e) }
      }
    } catch (error) {
      console.error("Failed to refresh server:", error)
    }
  }

  async function handleDeleteServer() {
    if (!serverToDelete) return
    try {
      await invoke("delete_server", { serverName: serverToDelete })
      await loadServers()
    } catch (error) {
      console.error("Delete error:", error)
    } finally {
      serverToDelete = null
    }
  }

  async function handleServerAdded(newServer: ServerInfo) {
    try {
      await invoke("add_server", { name: newServer.name, address: newServer.address, port: newServer.port })
    } catch (error) {
      console.error("Failed to save server:", error)
      alert(`Failed to add server: ${error}`)
      return
    }

    const statusData = await fetchServerStatus(newServer.address, newServer.port)

    if (statusData) {
      const serverWithStatus = { ...statusData, name: newServer.name }
      servers = [...servers, serverWithStatus]
      try {
        await invoke("update_server_status", { serverName: newServer.name, status: statusData })
      } catch (e) { console.error("Failed to save server status:", e) }
    } else {
      servers = [...servers, { ...newServer, status: "unknown" }]
    }
  }

  let filteredServers = $derived(
    servers.filter(server =>
      server.name.toLowerCase().includes(searchQuery.toLowerCase()) ||
      server.address.toLowerCase().includes(searchQuery.toLowerCase())
    )
  )

  let dragState: {
    fromIndex: number
    draggedOverIndex: number | null
    ghostEl: HTMLElement | null
    origCardEl: HTMLElement | null
    offsetY: number
    initialLeft: number
    minY: number
    maxY: number
  } | null = null

  let draggedOverIndex: number | null = $state(null)

  let pointerMoveImpl = (_e: PointerEvent) => {}
  let pointerUpImpl = (_e: PointerEvent) => {}
  let pointerCancelImpl = (_e: PointerEvent) => {}

  function stablePointerMove(e: PointerEvent) { pointerMoveImpl(e) }
  function stablePointerUp(e: PointerEvent) { pointerUpImpl(e) }
  function stablePointerCancel(e: PointerEvent) { pointerCancelImpl(e) }

  function cleanupDrag() {
    document.removeEventListener("pointermove", stablePointerMove)
    document.removeEventListener("pointerup", stablePointerUp)
    document.removeEventListener("pointercancel", stablePointerCancel)
    if (dragState) {
      if (dragState.ghostEl && dragState.ghostEl.parentNode) {
        dragState.ghostEl.parentNode.removeChild(dragState.ghostEl)
      }
      if (dragState.origCardEl) {
        dragState.origCardEl.style.opacity = ""
      }
    }
    dragState = null
    draggedOverIndex = null
  }

  pointerMoveImpl = (e: PointerEvent) => {
    const state = dragState
    if (!state || !state.ghostEl) return

    state.ghostEl.style.left = `${state.initialLeft}px`
    const clampedY = Math.max(state.minY, Math.min(e.clientY - state.offsetY, state.maxY))
    state.ghostEl.style.top = `${clampedY}px`

    const els = document.elementsFromPoint(e.clientX, e.clientY)
    for (const el of els) {
      if (el === state.ghostEl) continue
      const card = (el as HTMLElement).closest("[data-server-card]") as HTMLElement | null
      if (card && card !== state.ghostEl) {
        const idx = Number(card.dataset.serverIndex)
        if (!isNaN(idx) && idx !== state.draggedOverIndex) {
          state.draggedOverIndex = idx
          draggedOverIndex = idx
        }
        return
      }
    }
    if (state.draggedOverIndex !== null) {
      state.draggedOverIndex = null
      draggedOverIndex = null
    }
  }

  pointerUpImpl = (_e: PointerEvent) => {
    const state = dragState
    if (!state) return
    const fromIdx = state.fromIndex
    const toIdx = state.draggedOverIndex
    cleanupDrag()
    if (toIdx === null || fromIdx === toIdx) return

    const list = filteredServers
    const reordered = list.slice()
    const [moved] = reordered.splice(fromIdx, 1)
    reordered.splice(toIdx, 0, moved)

    if (searchQuery) {
      const movedNames = new Set(reordered.map(s => s.name))
      const remaining = servers.filter(s => !movedNames.has(s.name))
      persistReorder([...reordered, ...remaining])
    } else {
      persistReorder(reordered)
    }
  }

  pointerCancelImpl = (_e: PointerEvent) => {
    cleanupDrag()
  }

  async function persistReorder(ordered: ServerInfo[]) {
    servers = ordered
    try {
      await invoke("reorder_servers", { serverNames: ordered.map(s => s.name) })
    } catch (e) {
      console.error("Failed to reorder servers:", e)
    }
  }

  function handleGripPointerDown(e: PointerEvent, index: number) {
    if (searchQuery.trim()) return
    e.preventDefault()
    e.stopPropagation()

    const gripEl = e.currentTarget as HTMLElement
    const cardEl = gripEl.closest("[data-server-card]") as HTMLElement | null
    if (!cardEl) return

    const rect = cardEl.getBoundingClientRect()
    const offsetY = e.clientY - rect.top
    const initialLeft = rect.left

    const listEl = cardEl.parentElement
    let minY = -Infinity
    let maxY = Infinity
    if (listEl) {
      const listRect = listEl.getBoundingClientRect()
      minY = listRect.top
      maxY = listRect.bottom - rect.height
    }

    const ghost = cardEl.cloneNode(true) as HTMLElement
    ghost.removeAttribute("data-server-card")
    ghost.dataset.serverIndex = "-1"
    ghost.style.position = "fixed"
    ghost.style.left = `${initialLeft}px`
    ghost.style.top = `${e.clientY - offsetY}px`
    ghost.style.width = `${rect.width}px`
    ghost.style.pointerEvents = "none"
    ghost.style.zIndex = "9999"
    ghost.style.transform = "scale(1.03)"
    ghost.style.opacity = "0.95"
    ghost.style.transition = "none"
    ghost.style.outline = "none"
    ghost.style.willChange = "transform, left, top"
    document.body.appendChild(ghost)

    cardEl.style.opacity = "0.3"

    dragState = {
      fromIndex: index,
      draggedOverIndex: index,
      ghostEl: ghost,
      origCardEl: cardEl,
      offsetY,
      initialLeft,
      minY,
      maxY,
    }
    draggedOverIndex = index
    document.addEventListener("pointermove", stablePointerMove)
    document.addEventListener("pointerup", stablePointerUp)
    document.addEventListener("pointercancel", stablePointerCancel)
  }

  async function handleLaunchServer(server: ServerInfo, e: MouseEvent) {
    e.stopPropagation()
    if (server.status !== "online") {
      alert("Server must be online to connect")
      return
    }
    launchingServer = server.name
    try {
      await invoke("launch_server", {
        serverAddress: server.address,
        serverPort: server.port,
        serverName: server.name,
      })
      setTimeout(() => { launchingServer = null }, 1000)
    } catch (error) {
      console.error("Failed to launch server:", error)
      alert(`Failed to launch server: ${error}`)
      launchingServer = null
    }
  }
</script>

<div class="p-8 space-y-4">
  <div class="max-w-7xl mx-auto">
    <div class="flex items-center justify-between mb-4">
      <div class="flex items-center gap-2">
        {#if servers.length > 0}
          <div class="relative rounded-md bg-[var(--bg-tertiary)]">
            <Search size={16} class="absolute left-3 top-1/2 -translate-y-1/2 text-[var(--text-muted)] z-20 pointer-events-none" strokeWidth={2} />
            <input
              type="text"
              placeholder="Search servers..."
              bind:value={searchQuery}
              class="w-72 bg-transparent rounded-md pl-9 pr-3 py-1.5 text-sm text-[var(--text-primary)] placeholder-[var(--text-muted)] focus:outline-none transition-all relative z-10"
            />
          </div>
        {/if}
      </div>
      <div class="flex items-center gap-2">
        <button
          onclick={() => showAddModal = true}
          class="px-4 h-8 bg-[var(--accent-primary)] hover:bg-[var(--accent-hover)] text-white rounded-md text-sm font-medium flex items-center gap-2 transition-colors cursor-pointer"
        >
          <Plus size={16} />
          Add Server
        </button>
      </div>
    </div>

    {#if servers.length === 0}
      <div class="flex flex-col items-center justify-center py-14">
        <Server size={48} class="text-[var(--text-muted)] mb-3" strokeWidth={1.5} />
        <h3 class="text-base font-semibold text-[var(--text-primary)] mb-1">No servers added</h3>
        <p class="text-sm text-[var(--text-muted)] mb-4">Add your first server to get started</p>
        <button
          onclick={() => showAddModal = true}
          class="px-4 py-2 bg-[var(--accent-primary)] hover:bg-[var(--accent-hover)] text-white rounded font-medium text-sm flex items-center gap-2 transition-all cursor-pointer"
        >
          <Plus size={16} strokeWidth={2} />
          <span>Add Server</span>
        </button>
      </div>
    {:else if filteredServers.length === 0}
      <div class="rounded-md p-8 flex flex-col items-center justify-center">
        <Search size={48} class="text-[var(--text-primary)] mb-3" strokeWidth={1.5} />
        <h3 class="text-base font-semibold text-[var(--text-primary)] mb-1">No servers found</h3>
        <p class="text-sm text-[var(--text-muted)]">Try adjusting your search query</p>
      </div>
    {:else}
      <div class="space-y-4">
        {#each filteredServers as server, index (server.name)}
          {@const displayAddress = server.port === 25565 ? server.address : `${server.address}:${server.port}`}
          {@const isLaunching = launchingServer === server.name}
          {@const isOnline = server.status === "online"}
          {@const isOver = draggedOverIndex === index}
          <div
            data-server-card
            data-server-index={index}
            class="group flex items-center gap-3 px-4 rounded-md bg-[var(--bg-tertiary)] hover:bg-[var(--bg-hover)] {isOver ? 'outline outline-2 outline-[var(--accent-primary)]' : 'transition-colors'}"
            style="height: 100px"
          >
            <div
              role="presentation"
              onpointerdown={e => handleGripPointerDown(e, index)}
              class="flex-shrink-0 cursor-grab active:cursor-grabbing touch-none text-[var(--text-muted)] hover:text-[var(--text-primary)] transition-colors"
            >
              <GripVertical size={18} strokeWidth={2} />
            </div>
            <div class="flex-shrink-0">
              {#if server.favicon}
                <img
                  src={server.favicon}
                  alt={server.name}
                  class="w-20 h-20 rounded object-cover"
                  style="image-rendering: pixelated"
                />
              {:else}
                <div class="w-20 h-20 bg-[var(--bg-secondary)] rounded flex items-center justify-center">
                  <Server size={40} class="text-[var(--text-muted)]" strokeWidth={2} />
                </div>
              {/if}
            </div>

            <div class="flex-1 min-w-0">
              <p class="font-semibold text-xl text-[var(--text-primary)] truncate leading-none mb-2">{server.name}</p>
              {#if server.motd_html}
                <p class="text-base truncate leading-snug">{@html server.motd_html[0]}</p>
                {#if server.motd_html[1]}
                  <p class="text-base truncate leading-snug">{@html server.motd_html[1]}</p>
                {/if}
              {:else if server.motd}
                <p class="text-base text-[var(--text-muted)] truncate leading-snug">{server.motd.split("\n")[0]}</p>
                {#if server.motd.includes("\n")}
                  <p class="text-base text-[var(--text-muted)] truncate leading-snug">{server.motd.split("\n")[1]}</p>
                {/if}
              {:else}
                <p class="text-base text-[var(--text-muted)] truncate">{displayAddress}</p>
              {/if}
            </div>

            <div class="flex-shrink-0 flex flex-col items-end gap-2 group-hover:hidden">
              {#if isOnline}
                {#if server.ping === undefined}
                  <span class="text-base font-medium text-[var(--text-muted)]">N/A</span>
                {:else}
                  <span class="text-base font-medium" style="color: {server.ping < 80 ? '#16a34a' : server.ping < 200 ? '#eab308' : '#e93636'}">{server.ping}ms</span>
                {/if}
              {/if}
              {#if isOnline && server.players_online !== undefined}
                <span class="text-base text-[var(--text-muted)]">
                  {server.players_online}/{server.players_max}
                </span>
              {:else}
                <span class="text-base font-medium {server.status === 'offline' ? 'text-[#ef4444]' : 'text-[var(--text-muted)]'}">
                  {server.status === "offline" ? "Offline" : "-"}
                </span>
              {/if}
            </div>

            <div class="flex-shrink-0 items-center gap-2 hidden group-hover:flex">
              <button
                onclick={e => { e.stopPropagation(); serverToDelete = server.name }}
                class="w-10 h-10 flex items-center justify-center rounded text-[var(--text-muted)] hover:text-[#ef4444] hover:bg-[#ef4444]/10 transition-colors cursor-pointer"
              >
                <Trash2 size={18} strokeWidth={2} />
              </button>

              <button
                onclick={e => handleLaunchServer(server, e)}
                disabled={!isOnline || isLaunching || isAnyInstanceRunning}
                title={!isOnline ? "Server offline" : isAnyInstanceRunning ? "Instance already running" : undefined}
                class="flex-shrink-0 h-10 px-8 flex items-center justify-center gap-3 rounded transition-all active:scale-95 cursor-pointer {isLaunching || isAnyInstanceRunning ? 'bg-red-500/10 text-red-400 cursor-not-allowed' : isOnline ? 'bg-[#16a34a] hover:bg-[#15803d] text-[#181a1f]' : 'bg-[var(--bg-hover-strong)] text-[var(--text-muted)] cursor-not-allowed'} disabled:opacity-50"
              >
                {#if isLaunching || isAnyInstanceRunning}
                  <div class="w-5 h-5 border-2 border-red-400/30 border-t-red-400 rounded-full animate-spin"></div>
                {:else}
                  <Play size={18} fill="currentColor" strokeWidth={0} />
                  <span class="text-base font-semibold">Join</span>
                {/if}
              </button>
            </div>
          </div>
        {/each}
      </div>
    {/if}
  </div>
</div>

{#if showAddModal}
  <CreateServerModal
    {servers}
    onClose={() => showAddModal = false}
    onSuccess={handleServerAdded}
  />
{/if}

<ConfirmModal
  isOpen={serverToDelete !== null}
  title="Remove Server"
  message={`Are you sure you want to remove "${serverToDelete}"? This action cannot be undone.`}
  confirmText="Remove"
  cancelText="Cancel"
  type="danger"
  onConfirm={handleDeleteServer}
  onCancel={() => serverToDelete = null}
/>
