// frontend/features/skins/SkinsTab.svelte
<script lang="ts">
  import { invoke } from "@tauri-apps/api/core"
  import { Upload, Loader2, User, RotateCcw, Save, Plane, RectangleVertical } from "lucide-svelte"
  import * as skinview3d from "skinview3d"
  import type { RecentSkin, Cape } from "../../types"
  import { storeGet, storeSet, storeRemove } from "../../lib/store"
  import { store } from "../../lib/launcherStore.svelte"
  import { untrack } from "svelte"

  const SKIN_CACHE_KEY = "octane_skin_cache"
  const CAPE_CACHE_KEY = "octane_cape_cache"
  const CACHE_DURATION = 15 * 60 * 1000
  const MIN_FETCH_INTERVAL = 10 * 1000

  function loadCache<T>(key: string): Promise<T | null> {
    return storeGet<T>(key).then(v => v ?? null)
  }

  function saveCache<T>(key: string, data: T) {
    return storeSet(key, data)
  }

  const canFetch = (last: number) => Date.now() - last >= MIN_FETCH_INTERVAL

  type PersistedSkinCache = { uuid: string; url: string; variant: string; timestamp: number }
  type PersistedCapeCache = { uuid: string; capes: Cape[]; activeCapeId: string | null; timestamp: number }

  let loading = $state(true)
  let error = $state<string | null>(null)
  let uploading = $state(false)
  let skinVariant = $state<"classic" | "slim">("classic")
  let capes = $state<Cape[]>([])
  let activeCape = $state<string | null>(null)
  let loadingCapes = $state(false)
  let showElytra = $state(false)
  let recentSkins = $state<RecentSkin[]>([])
  let currentSkinUrl = $state<string | null>(null)
  let containerSize = $state({ width: 800, height: 600 })
  let hasPendingChanges = $state(false)
  let saving = $state(false)

  let containerEl: HTMLDivElement | undefined = $state()
  let canvasEl: HTMLCanvasElement | undefined = $state()
  let fileInputEl: HTMLInputElement | undefined = $state()

  let viewer = $state<skinview3d.SkinViewer | null>(null)
  let skinResetTimeout: ReturnType<typeof setTimeout> | undefined
  let dragState = { active: false, startX: 0, startRot: 0.3 }
  let lastProfileFetch: Record<string, number> = {}
  let lastCapeFetch: Record<string, number> = {}
  let originalState = { skinUrl: null as string | null, variant: 'classic' as 'classic' | 'slim', activeCape: null as string | null }
  let pendingSkinOp: { type: 'upload'; base64: string; variant: 'classic' | 'slim' } | { type: 'recent'; url: string; variant: 'classic' | 'slim' } | { type: 'reset' } | null = null
  let pendingCapeOp: { type: 'select'; capeId: string } | { type: 'remove' } | null = null
  let loadUserSkinFn: (forceRefresh?: boolean) => Promise<void> = async () => {}

  let prevSkinUrl: string | undefined
  $effect(() => {
    store.activeAccount
    untrack(() => {
      if (prevSkinUrl?.startsWith('blob:')) URL.revokeObjectURL(prevSkinUrl)
      prevSkinUrl = currentSkinUrl ?? undefined
      pendingSkinOp = null
      pendingCapeOp = null
      hasPendingChanges = false
    })
  })

  $effect(() => {
    if (!store.activeAccount) { recentSkins = []; return }
    loadRecentSkins()
  })

  $effect(() => { loadUserSkin() })

  async function loadRecentSkins() {
    if (!store.activeAccount) return
    try {
      const result = await invoke<RecentSkin[]>("load_recent_skins", { accountUuid: store.activeAccount.uuid })
      recentSkins = Array.isArray(result) ? result : []
    } catch { recentSkins = [] }
  }

  async function addToRecentSkins(url: string, variant: "classic" | "slim") {
    if (!store.activeAccount) return
    recentSkins = [{ url, variant, timestamp: Date.now() }, ...recentSkins.filter(s => s.url !== url)].slice(0, 3)
    try { await invoke<void>("save_recent_skin", { accountUuid: store.activeAccount.uuid, skinUrl: url, variant }) }
    catch { console.error("Failed to save recent skin") }
  }

  function applyUploadedSkin(result: { url: string; variant: string }): "classic" | "slim" | null {
    if (!result?.url) return null
    const variant: "classic" | "slim" = result.variant === "slim" ? "slim" : "classic"
    skinVariant = variant
    currentSkinUrl = result.url
    if (store.activeAccount) {
      saveCache<PersistedSkinCache>(SKIN_CACHE_KEY, {
        uuid: store.activeAccount.uuid, url: result.url, variant, timestamp: Date.now(),
      })
    }
    return variant
  }

  const CAPE_TEX_W = 64
  const CAPE_FRONT = { x: 1, y: 1, w: 10, h: 16 }
  const CAPE_THUMB_SCALE = 2

  function normalizeCapeUrl(url: string) { return url.replace("http://", "https://") }

  async function loadUserSkin(forceRefresh = false) {
    if (!store.isAuthenticated || !store.activeAccount) {
      loading = false; error = "Please sign in to view your skin"; return
    }
    try {
      loading = true; error = null
      const now = Date.now()
      const persisted = await loadCache<PersistedSkinCache>(SKIN_CACHE_KEY)
      const cacheValid =
        persisted && persisted.uuid === store.activeAccount.uuid && (now - persisted.timestamp) < CACHE_DURATION

      const applyCached = () => {
        if (!cacheValid) return
        currentSkinUrl = persisted!.url
        skinVariant = persisted!.variant as "classic" | "slim"
        originalState = { ...originalState, skinUrl: persisted!.url, variant: persisted!.variant as "classic" | "slim" }
      }

      if (!forceRefresh && cacheValid) { applyCached(); loading = false; loadCapes(); return }
      if (!canFetch(lastProfileFetch[store.activeAccount.uuid] ?? 0)) { applyCached(); loading = false; loadCapes(); return }

      lastProfileFetch[store.activeAccount.uuid] = now
      const skinData = await invoke<{ url: string; variant: string }>("get_current_skin")
      if (skinData?.url) {
        const variant = skinData.variant === "slim" ? "slim" : "classic"
        currentSkinUrl = skinData.url
        skinVariant = variant
        originalState = { ...originalState, skinUrl: skinData.url, variant }
        await saveCache<PersistedSkinCache>(SKIN_CACHE_KEY, {
          uuid: store.activeAccount.uuid, url: skinData.url, variant, timestamp: now,
        })
      } else {
        currentSkinUrl = null
      }
      loading = false; loadCapes()
    } catch (err: unknown) {
      if (typeof err === "string" && err.includes("429")) {
        error = "Rate limited — please wait before refreshing."
        const persisted = await loadCache<PersistedSkinCache>(SKIN_CACHE_KEY)
        if (persisted && persisted.uuid === store.activeAccount?.uuid) {
          currentSkinUrl = persisted.url
          skinVariant = persisted.variant as "classic" | "slim"
          originalState = { ...originalState, skinUrl: persisted.url, variant: persisted.variant as "classic" | "slim" }
        }
      } else {
        error = `Failed to load skin: ${String(err)}`; currentSkinUrl = null
      }
      loading = false
    }
  }
  loadUserSkinFn = loadUserSkin

  async function loadCapes() {
    if (!store.isAuthenticated || !store.activeAccount) return
    const now = Date.now()
    const persisted = await loadCache<PersistedCapeCache>(CAPE_CACHE_KEY)
    const cacheValid =
      persisted && persisted.uuid === store.activeAccount.uuid && (now - persisted.timestamp) < CACHE_DURATION
    if (cacheValid) {
      capes = persisted!.capes.map(c => ({ ...c, url: normalizeCapeUrl(c.url) })); activeCape = persisted!.activeCapeId
      originalState = { ...originalState, activeCape: persisted!.activeCapeId }
      return
    }

    capes = []; activeCape = null
    if (!canFetch(lastCapeFetch[store.activeAccount.uuid] ?? 0)) return
    try {
      loadingCapes = true
      lastCapeFetch[store.activeAccount.uuid] = now
      const capeData = await invoke<{ capes: Cape[] }>("get_user_capes")
      if (capeData?.capes) {
        capes = capeData.capes.map(c => ({ ...c, url: normalizeCapeUrl(c.url) }))
        const activeId = capeData.capes.find((c: Cape) => c.state === "ACTIVE")?.id ?? null
        activeCape = activeId
        originalState = { ...originalState, activeCape: activeId }
        await saveCache<PersistedCapeCache>(CAPE_CACHE_KEY, {
          uuid: store.activeAccount.uuid, capes: capeData.capes, activeCapeId: activeId, timestamp: now,
        })
      }
    } catch { console.error("Failed to load capes") } finally { loadingCapes = false }
  }

  function handleCapeSelect(capeId: string) {
    activeCape = capeId
    pendingCapeOp = { type: 'select', capeId }
    hasPendingChanges = true
  }

  function handleCapeRemove() {
    activeCape = null
    pendingCapeOp = { type: 'remove' }
    hasPendingChanges = true
  }

  function handleFileSelect(event: Event) {
    const input = event.target as HTMLInputElement
    const file = input.files?.[0]
    if (!file) return
    const localUrl = URL.createObjectURL(file)
    uploading = true
    currentSkinUrl = localUrl
    const reader = new FileReader()
    reader.onload = (e) => {
      const base64 = ((e.target?.result) as string).split(",")[1]
      pendingSkinOp = { type: 'upload', base64, variant: skinVariant }
      hasPendingChanges = true
      uploading = false
    }
    reader.readAsDataURL(file)
  }

  function handleReset() {
    pendingSkinOp = { type: 'reset' }
    hasPendingChanges = true
  }

  function handleRecentSkinSelect(skin: RecentSkin) {
    currentSkinUrl = skin.url
    skinVariant = skin.variant
    pendingSkinOp = { type: 'recent', url: skin.url, variant: skin.variant }
    hasPendingChanges = true
  }

  async function handleSave() {
    saving = true; error = null
    let finalSkinUrl = currentSkinUrl
    let finalVariant = skinVariant
    let finalCape = activeCape
    try {
      const skinOp = pendingSkinOp
      if (skinOp) {
        if (skinOp.type === 'upload') {
          const result = await invoke<{ url: string; variant: string }>('upload_skin', { skinData: skinOp.base64, variant: skinVariant })
          const variant = applyUploadedSkin(result)
          finalSkinUrl = result.url
          finalVariant = variant ?? finalVariant
          if (variant) await addToRecentSkins(result.url, variant)
        } else if (skinOp.type === 'recent') {
          const response = await fetch(skinOp.url)
          const blob = await response.blob()
          const base64 = await new Promise<string>((resolve, reject) => {
            const reader = new FileReader()
            reader.onload = () => resolve((reader.result as string).split(',')[1])
            reader.onerror = reject
            reader.readAsDataURL(blob)
          })
          const result = await invoke<{ url: string; variant: string }>('upload_skin', { skinData: base64, variant: skinVariant })
          const variant = applyUploadedSkin(result)
          finalSkinUrl = result.url
          finalVariant = variant ?? finalVariant
          if (variant) await addToRecentSkins(result.url, variant)
        } else if (skinOp.type === 'reset') {
          await invoke<void>('reset_skin')
          await storeRemove(SKIN_CACHE_KEY)
          skinResetTimeout = setTimeout(() => loadUserSkinFn(false), 2000)
        }
      }

      const capeOp = pendingCapeOp
      if (capeOp) {
        if (capeOp.type === 'select') {
          await invoke<void>('equip_cape', { capeId: capeOp.capeId })
          finalCape = capeOp.capeId
        } else if (capeOp.type === 'remove') {
          await invoke<void>('remove_cape')
          finalCape = null
        }
        if (store.activeAccount) {
          const cached = await loadCache<PersistedCapeCache>(CAPE_CACHE_KEY)
          if (cached?.uuid === store.activeAccount.uuid) {
            await saveCache(CAPE_CACHE_KEY, { ...cached, activeCapeId: finalCape, timestamp: Date.now() })
          }
        }
      }

      if (currentSkinUrl?.startsWith('blob:')) URL.revokeObjectURL(currentSkinUrl)
      originalState = { skinUrl: finalSkinUrl, variant: finalVariant, activeCape: finalCape }
      pendingSkinOp = null
      pendingCapeOp = null
      hasPendingChanges = false
    } catch (err) {
      error = `Save failed: ${err}`
    } finally {
      saving = false
    }
  }

  function handleDiscard() {
    if (currentSkinUrl?.startsWith('blob:')) URL.revokeObjectURL(currentSkinUrl)
    pendingSkinOp = null
    pendingCapeOp = null
    currentSkinUrl = originalState.skinUrl
    skinVariant = originalState.variant
    activeCape = originalState.activeCape
    hasPendingChanges = false
    error = null
  }

  let activeCapeObj = $derived(capes.find(c => c.id === activeCape) ?? null)
  let activeCapeUrl = $derived<string | null>(activeCapeObj?.url ?? null)

  // SkinViewer3D initialization
  $effect(() => {
    const canvas = canvasEl
    const container = containerEl
    if (!canvas || !container) return

    const { width: cw, height: ch } = container.getBoundingClientRect()
    const v = new skinview3d.SkinViewer({ canvas, width: Math.round(cw), height: Math.round(ch) })

    v.renderer.setClearColor(0x000000, 0)
    v.globalLight.intensity = 3.0
    v.cameraLight.intensity = 0.0
    v.animation = new skinview3d.IdleAnimation()
    v.animation.speed = 1
    v.controls.enabled = false
    v.fov = 70
    v.zoom = 0.6
    v.playerObject.rotation.y = 0.3
    v.camera.position.y += 8
    v.camera.lookAt(v.playerObject.position)

    const ro = new ResizeObserver(entries => {
      const { width, height } = entries[0].contentRect
      containerSize = { width: Math.round(width), height: Math.round(height) }
    })
    ro.observe(container)

    viewer = v

    return () => {
      ro.disconnect()
      v.dispose()
      viewer = null
    }
  })

  $effect(() => {
    const v = viewer
    if (!v) return
    const { width, height } = containerSize
    if (width < 1 || height < 1) return
    v.setSize(width, height)
    v.render()
  })

  $effect(() => {
    const v = viewer
    if (!v) return
    if (currentSkinUrl) {
      v.loadSkin(currentSkinUrl, { model: skinVariant === "slim" ? "slim" : "default" })
    } else {
      v.loadSkin(null)
    }
  })

  $effect(() => {
    const v = viewer
    if (!v) return
    if (activeCapeUrl) {
      v.loadCape(activeCapeUrl, showElytra ? { backEquipment: "elytra" } : undefined)
    } else {
      v.loadCape(null)
    }
  })

  $effect(() => {
    const timeout = skinResetTimeout
    return () => clearTimeout(timeout)
  })

  function handlePointerDown(e: PointerEvent) {
    if ((e.target as HTMLElement).closest("button, input")) return
    dragState = {
      active: true,
      startX: e.clientX,
      startRot: viewer?.playerObject.rotation.y ?? 0.3,
    }
    ;(e.currentTarget as HTMLElement)?.setPointerCapture?.(e.pointerId)
  }

  function handlePointerMove(e: PointerEvent) {
    if (!dragState.active || !viewer) return
    const dx = e.clientX - dragState.startX
    viewer.playerObject.rotation.y = dragState.startRot + dx * 0.01
  }

  function handlePointerUp() { dragState.active = false }
  function handlePointerCancel() { dragState.active = false }
</script>

{#if !store.isAuthenticated}
  <div class="p-8 space-y-4">
    <div class="max-w-7xl mx-auto">
      <div class="mb-6">
        <h1 class="text-2xl font-semibold text-[var(--text-primary)] tracking-tight">Sign In</h1>
      </div>
      <div class="flex flex-col items-center justify-center min-h-[calc(100vh-300px)]">
        <User size={64} class="text-[#4572e3] mb-4" strokeWidth={1.5} />
        <h3 class="text-lg font-semibold text-[var(--text-primary)] mb-1">Sign In Required</h3>
        <p class="text-sm text-[var(--text-muted)]">
          Please sign in with your Microsoft account to manage your skin
        </p>
      </div>
    </div>
  </div>
{:else}
  <div
    role="presentation"
    bind:this={containerEl}
    style="position: relative; overflow: hidden; height: 100%; box-sizing: border-box; user-select: none; -webkit-user-select: none;"
    onpointerdown={handlePointerDown}
    onpointermove={handlePointerMove}
    onpointerup={handlePointerUp}
    onpointercancel={handlePointerCancel}
  >
    <div style="position: absolute; inset: 0; z-index: 0; pointer-events: none;">
      <div style="width: 100%; height: 100%; position: relative; overflow: hidden; background-image: url(/skinstab/background.webp); background-size: cover; background-position: center; background-repeat: no-repeat;">
        <div style="position: absolute; inset: 0; background: rgba(0,0,0,0.35); z-index: 1;"></div>
        <div style="position: absolute; inset: 0; z-index: 3; display: flex; flex-direction: column; align-items: center; justify-content: center; pointer-events: none; opacity: {loading ? 1 : 0}; transition: opacity 0.15s;">
          <Loader2 size={32} style="animation: spin 1s linear infinite; color: #3b82f6; margin-bottom: 12px;" />
          <p style="font-size: 14px; color: var(--text-muted); margin: 0;">Loading skin…</p>
        </div>
        <canvas
          bind:this={canvasEl}
          style="display: block; position: relative; z-index: 2; opacity: {loading ? 0 : 1}; transition: opacity 0.2s; width: 100%; height: 100%;"
        ></canvas>
      </div>
    </div>

    <div style="position: relative; z-index: 1; height: 100%; box-sizing: border-box; padding: 32px 32px 88px;">
      <div class="max-w-7xl mx-auto w-full">
        <div class="flex items-center justify-between mb-6">
          <h1 class="text-2xl font-semibold text-[var(--text-primary)] tracking-tight">
            {store.activeAccount?.username ?? "Skins"}
          </h1>
        </div>
      </div>

      {#if error}
        <div style="position: absolute; top: 50%; left: 50%; transform: translate(-50%, -50%); pointer-events: auto;">
          <div class="bg-[var(--bg-tertiary)] rounded-md p-4 max-w-sm w-full">
            <p class="text-xs text-red-400 leading-relaxed text-center">{error}</p>
          </div>
        </div>
      {/if}
    </div>

    <input bind:this={fileInputEl} type="file" accept="image/png" onchange={handleFileSelect} class="hidden" />

    {#snippet tip(text: string)}
      <div class="absolute bottom-[calc(100%+6px)] left-1/2 -translate-x-1/2 px-[7px] py-[3px] rounded border border-[var(--border-color,#333)] bg-[var(--bg-secondary,#1a1a2e)] text-[var(--text-primary,#eee)] text-[11px] whitespace-nowrap pointer-events-none z-[100] hidden group-hover:block">{text}</div>
    {/snippet}

    <div
      role="presentation"
      onpointerdown={(e) => e.stopPropagation()}
      style="position: absolute; bottom: 32px; left: 50%; transform: translateX(-50%); z-index: 10; display: flex; align-items: center; gap: 12px; max-width: calc(100% - 64px); flex-wrap: wrap; justify-content: center;"
    >
      <div style="display: flex; align-items: center; gap: 6px; padding: 6px 10px; border-radius: 12px; background: var(--bg-elevated); backdrop-filter: blur(12px); justify-content: center;">
        <div role="presentation" class="group relative inline-flex">
          <button
            onclick={() => fileInputEl?.click()}
            disabled={uploading || loading}
            class="flex items-center justify-center w-[34px] h-[34px] rounded-md bg-transparent text-[#16a34a] transition-colors shrink-0 enabled:hover:bg-[var(--bg-hover)] enabled:cursor-pointer disabled:cursor-not-allowed disabled:opacity-40"
          >
            {#if uploading}
              <Loader2 size={20} class="animate-spin" />
            {:else}
              <Upload size={20} strokeWidth={2.5} />
            {/if}
          </button>
          {@render tip("Upload skin")}
        </div>

        <div role="presentation" class="group relative inline-flex">
          <button
            onclick={handleReset}
            disabled={loading}
            class="flex items-center justify-center w-[34px] h-[34px] rounded-md bg-transparent text-[var(--text-muted)] transition-colors shrink-0 enabled:hover:bg-[var(--bg-hover)] enabled:cursor-pointer disabled:cursor-not-allowed disabled:opacity-40"
          >
            <RotateCcw size={20} strokeWidth={2.5} />
          </button>
          {@render tip("Reset to default skin")}
        </div>

        <button
          onclick={() => skinVariant = "classic"}
          class="px-[10px] py-[6px] rounded-lg text-[13px] font-semibold tracking-[0.01em] whitespace-nowrap box-border transition-colors cursor-pointer shrink-0 {skinVariant === 'classic' ? 'bg-[var(--accent-primary,#4572e3)] text-white' : 'bg-[var(--bg-secondary)] text-[var(--text-muted)] hover:bg-[var(--bg-hover,#2a2a3e)]'}"
        >
          Classic
        </button>
        <button
          onclick={() => skinVariant = "slim"}
          class="px-[10px] py-[6px] rounded-lg text-[13px] font-semibold tracking-[0.01em] whitespace-nowrap box-border transition-colors cursor-pointer shrink-0 {skinVariant === 'slim' ? 'bg-[var(--accent-primary,#4572e3)] text-white' : 'bg-[var(--bg-secondary)] text-[var(--text-muted)] hover:bg-[var(--bg-hover,#2a2a3e)]'}"
        >
          Slim
        </button>

        {#if loadingCapes || capes.length > 0}
          <!-- CapeBar -->
          {#if loadingCapes}
            <div style="display: flex; align-items: center; gap: 4px;">
              <Loader2 size={14} style="animation: spin 1s linear infinite; color: var(--text-muted);" />
              <span style="font-size: 11px; color: var(--text-muted);">Capes…</span>
            </div>
          {:else if capes.length === 0}
            <span style="font-size: 11px; color: var(--text-muted);">No capes</span>
          {:else}
            <div style="display: flex; align-items: center; gap: 3px;">
              {#each capes as cape (cape.id)}
                {@const isActive = activeCape === cape.id}
                <div role="presentation" class="group relative inline-flex">
                  <div
                    role="button"
                    tabindex="0"
                    onclick={() => isActive ? handleCapeRemove() : handleCapeSelect(cape.id)}
                    onkeydown={(e) => { if (e.key === 'Enter') isActive ? handleCapeRemove() : handleCapeSelect(cape.id) }}
                    class="cursor-pointer shrink-0 leading-none"
                  >
                    <div class="w-[26px] h-[38px] rounded border-2 border-transparent group-hover:border-[var(--text-muted)] overflow-hidden bg-[var(--bg-secondary)] transition-colors relative flex items-center justify-center">
                      <div style="width: {CAPE_FRONT.w * CAPE_THUMB_SCALE}px; height: {CAPE_FRONT.h * CAPE_THUMB_SCALE}px; overflow: hidden; flex-shrink: 0;">
                        <img
                          src={cape.url}
                          alt={cape.alias}
                          draggable={false}
                          style="width: {CAPE_TEX_W * CAPE_THUMB_SCALE}px; max-width: none; height: auto; margin-left: {-CAPE_FRONT.x * CAPE_THUMB_SCALE}px; margin-top: {-CAPE_FRONT.y * CAPE_THUMB_SCALE}px; image-rendering: pixelated; display: block;"
                          onerror={(e) => { const img = e.currentTarget as HTMLImageElement; img.onerror = null; img.src = '/logo.png' }}
                        />
                      </div>
                      {#if isActive}
                        <div class="absolute inset-0 flex items-center justify-center bg-black/45">
                          <svg width="16" height="16" viewBox="0 0 12 12" fill="none">
                            <path d="M2 6L5 9L10 3" stroke="#22c55e" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round" class="group-hover:stroke-[#ef4444]" />
                          </svg>
                        </div>
                      {/if}
                    </div>
                  </div>
                  {@render tip(cape.alias)}
                </div>
              {/each}
            </div>
          {/if}

          {#if activeCapeUrl}
            <div role="presentation" class="group relative inline-flex">
              <button
                onclick={() => showElytra = !showElytra}
                class="flex items-center justify-center w-[34px] h-[34px] rounded-md bg-transparent hover:bg-[var(--bg-hover)] text-[var(--text-muted)] transition-colors cursor-pointer shrink-0"
              >
                {#if showElytra}
                  <RectangleVertical size={20} strokeWidth={2.5} />
                {:else}
                  <Plane size={20} strokeWidth={2.5} />
                {/if}
              </button>
              {@render tip(showElytra ? "Show as cape" : "Show as elytra")}
            </div>
          {/if}
        {/if}

        {#if hasPendingChanges}
          <div class="flex gap-2 ml-auto shrink-0">
            <button
              onclick={handleDiscard}
              disabled={saving}
              class="px-4 py-1.5 rounded-lg bg-[var(--bg-secondary,#1a1a2e)] text-[var(--text-muted,#888)] text-[13px] font-semibold transition-colors shrink-0 enabled:hover:bg-[var(--bg-hover,#2a2a3e)] enabled:cursor-pointer disabled:cursor-not-allowed disabled:opacity-50"
            >
              Cancel
            </button>
            <button
              onclick={handleSave}
              disabled={saving}
              class="px-4 py-1.5 rounded-lg bg-[#16a34a] enabled:hover:bg-[#15803d] text-white text-[13px] font-semibold transition-colors flex items-center gap-1.5 shrink-0 enabled:cursor-pointer disabled:cursor-not-allowed disabled:opacity-60"
            >
              {#if saving}
                Saving…
              {:else}
                <Save size={16} strokeWidth={2.5} /> Save
              {/if}
            </button>
          </div>
        {/if}
      </div>

      {#if recentSkins.length > 0}
        <div style="display: flex; align-items: center; gap: 4px; padding: 5px 6px; border-radius: 12px; background: var(--bg-elevated); backdrop-filter: blur(12px); flex-shrink: 0;">
          {#each recentSkins as skin}
            {@const match = skin.url.match(/texture\/([a-f0-9]+)/)}
            {@const hash = match ? match[1] : null}
            {@const bustUrl = hash ? `https://renders.stellarmc.gg/bust/${hash}${skin.variant === "slim" ? "?slim" : ""}` : skin.url}
            <div role="presentation" class="group relative inline-flex">
              <button
                onclick={() => handleRecentSkinSelect(skin)}
                disabled={uploading}
                class="box-border w-10 h-10 rounded-md p-0 border-2 border-transparent group-hover:border-[var(--text-muted)] overflow-hidden bg-transparent transition-colors shrink-0 enabled:cursor-pointer disabled:cursor-not-allowed disabled:opacity-40"
              >
                <img
                  src={bustUrl}
                  alt="Recent skin"
                  draggable={false}
                  class="w-full h-full object-cover block"
                  style="image-rendering: pixelated"
                />
              </button>
              {@render tip("Apply recent skin")}
            </div>
          {/each}
        </div>
      {/if}
    </div>
  </div>
{/if}

// frontend/features/skins/SkinsTab.tsx
import { useEffect, useRef, useState } from "react"
import { invoke } from "@tauri-apps/api/core"
import { Upload, RotateCcw, Loader2, User, X, Rotate3d, Settings } from "lucide-react"
import type { RecentSkin, Cape } from "../../types"

interface SkinsTabProps {
  activeAccount?: { uuid: string; username: string } | null
  isAuthenticated?: boolean
}

const SKIN_CACHE_KEY = "octane_skin_cache"
const CAPE_CACHE_KEY = "octane_cape_cache"
const CACHE_DURATION = 15 * 60 * 1000
const MIN_FETCH_INTERVAL = 10 * 1000

const CAPE_IMAGE_MAP: Record<string, string> = {
  "migrator": "migrator",
  "pan": "pan",
  "15th anniversary": "15th",
  "common": "common",
  "vanilla": "vanilla",
  "cherry blossom": "cherry",
  "purple heart": "twitch",
  "follower's": "tiktok",
  "menace": "menace",
  "copper": "copper",
  "home": "home",
  "mojang office": "mojangoffice",
  "yearn": "yearn",
  "founders": "founders",
  "zombie horse": "zombiehorse",
  "mcc 15th year": "mcc",
  "builder": "builder",
  "minecraft experience": "mcexp",
  "minecon 2016": "2016",
  "minecon 2015": "2015",
  "minecon 2013": "2013",
  "minecon 2012": "2012",
  "crafter": "crafter",
  "minecon 2011": "2011",
  "moonlight trail": "moonlighttrail",
  "realms mapmaker": "realms",
  "mojang": "mojang",
  "mojang studios": "mojangstudios"
}

function loadCache<T>(key: string): T | null {
  try {
    const raw = sessionStorage.getItem(key)
    if (!raw) return null
    return JSON.parse(raw) as T
  } catch { return null }
}

function saveCache<T>(key: string, data: T) {
  try { sessionStorage.setItem(key, JSON.stringify(data)) } catch {}
}

type PersistedSkinCache = { uuid: string; url: string; variant: string; timestamp: number }
type PersistedCapeCache = { uuid: string; capes: Cape[]; activeCapeId: string | null; timestamp: number }

export function SkinsTab(props: SkinsTabProps) {
  const { activeAccount, isAuthenticated } = props
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)
  const [uploading, setUploading] = useState(false)
  const [resetting, setResetting] = useState(false)
  const [skinVariant, setSkinVariant] = useState<"classic" | "slim">("classic")
  const [capes, setCapes] = useState<Cape[]>([])
  const [activeCape, setActiveCape] = useState<string | null>(null)
  const [loadingCapes, setLoadingCapes] = useState(false)
  const [recentSkins, setRecentSkins] = useState<RecentSkin[]>([])
  const [currentSkinHash, setCurrentSkinHash] = useState<string | null>(null)
  const [skinSettingsOpen, setSkinSettingsOpen] = useState(false)
  const [settingsClosing, setSettingsClosing] = useState(false)
  const [showBack, setShowBack] = useState(false)
  const fileInputRef = useRef<HTMLInputElement>(null)
  const lastProfileFetchRef = useRef<number>(0)
  const lastCapeFetchRef = useRef<Record<string, number>>({})

  useEffect(() => {
    if (!activeAccount || !invoke) { setRecentSkins([]); return }
    loadRecentSkins()
  }, [activeAccount, invoke])

  const loadRecentSkins = async () => {
    if (!activeAccount || !invoke) return
    try {
      const result = await invoke<RecentSkin[]>("load_recent_skins", { accountUuid: activeAccount.uuid })
      setRecentSkins(Array.isArray(result) ? result : [])
    } catch { setRecentSkins([]) }
  }

  const addToRecentSkins = async (url: string, variant: "classic" | "slim") => {
    if (!activeAccount || !invoke) return
    const newSkin: RecentSkin = { url, variant, timestamp: Date.now() }
    setRecentSkins(prev => [newSkin, ...prev.filter(s => s.url !== url)].slice(0, 3))
    try {
      await invoke<void>("save_recent_skin", { accountUuid: activeAccount.uuid, skinUrl: url, variant })
    } catch { console.error("Failed to save recent skin") }
  }

  useEffect(() => { loadUserSkin() }, [activeAccount])

  const getCapeImageName = (alias: string) => {
    return CAPE_IMAGE_MAP[alias.toLowerCase()] ?? "unknown"
  }

  const canFetchProfile = () => Date.now() - lastProfileFetchRef.current >= MIN_FETCH_INTERVAL
  const canFetchCapes = (uuid: string) => Date.now() - (lastCapeFetchRef.current[uuid] ?? 0) >= MIN_FETCH_INTERVAL

  const loadUserSkin = async (forceRefresh: boolean = false) => {
    if (!isAuthenticated || !activeAccount || !invoke) {
      setLoading(false)
      setError("Please sign in to view your skin")
      return
    }
    try {
      setLoading(true)
      setError(null)

      const now = Date.now()
      const persisted = loadCache<PersistedSkinCache>(SKIN_CACHE_KEY)
      const cacheValid = persisted && persisted.uuid === activeAccount.uuid && (now - persisted.timestamp) < CACHE_DURATION

      if (!forceRefresh && cacheValid) {
        const match = persisted!.url.match(/texture\/([a-f0-9]+)/)
        if (match) { setCurrentSkinHash(match[1]) }
        setSkinVariant(persisted!.variant as "classic" | "slim")
        setLoading(false)
        loadCapes()
        return
      }

      if (!canFetchProfile()) {
        if (cacheValid) {
          const match = persisted!.url.match(/texture\/([a-f0-9]+)/)
          if (match) { setCurrentSkinHash(match[1]) }
          setSkinVariant(persisted!.variant as "classic" | "slim")
        }
        setLoading(false)
        loadCapes()
        return
      }

      lastProfileFetchRef.current = now
      const skinData = await invoke<{ url: string; variant: string }>("get_current_skin")
      if (skinData && skinData.url) {
        const variant = skinData.variant === "slim" ? "slim" : "classic"
        const match = skinData.url.match(/texture\/([a-f0-9]+)/)
        if (match) { setCurrentSkinHash(match[1]) }
        setSkinVariant(variant)
        saveCache<PersistedSkinCache>(SKIN_CACHE_KEY, { uuid: activeAccount.uuid, url: skinData.url, variant, timestamp: now })
      } else {
        setCurrentSkinHash(null)
      }
      setLoading(false)
      loadCapes()
    } catch (err: any) {
      console.error("Failed to load skin:", err)
      if (err && typeof err === 'string' && err.includes('429')) {
        setError('Rate limited. Please wait before refreshing.')
        const persisted = loadCache<PersistedSkinCache>(SKIN_CACHE_KEY)
        if (persisted && persisted.uuid === activeAccount.uuid) {
          const match = persisted.url.match(/texture\/([a-f0-9]+)/)
          if (match) { setCurrentSkinHash(match[1]) }
          setSkinVariant(persisted.variant as "classic" | "slim")
        }
      } else {
        setError(`Failed to load skin: ${err}`)
        setCurrentSkinHash(null)
      }
      setLoading(false)
    }
  }

  const loadCapes = async () => {
    if (!invoke || !isAuthenticated || !activeAccount) return
    const now = Date.now()
    const persisted = loadCache<PersistedCapeCache>(CAPE_CACHE_KEY)
    const cacheValid = persisted && persisted.uuid === activeAccount.uuid && (now - persisted.timestamp) < CACHE_DURATION

    if (cacheValid) {
      setCapes(persisted!.capes)
      setActiveCape(persisted!.activeCapeId)
      return
    }

    setCapes([])
    setActiveCape(null)

    if (!canFetchCapes(activeAccount.uuid)) return

    try {
      setLoadingCapes(true)
      lastCapeFetchRef.current[activeAccount.uuid] = now
      const capeData = await invoke<{ capes: Cape[] }>("get_user_capes")
      if (capeData && capeData.capes) {
        setCapes(capeData.capes)
        const active = capeData.capes.find((cape: Cape) => cape.state === "ACTIVE")
        const activeId = active?.id || null
        setActiveCape(activeId)
        saveCache<PersistedCapeCache>(CAPE_CACHE_KEY, { uuid: activeAccount.uuid, capes: capeData.capes, activeCapeId: activeId, timestamp: now })
      }
    } catch { console.error("Failed to load capes") } finally { setLoadingCapes(false) }
  }

  const handleCloseSettings = () => {
    setSettingsClosing(true)
    setTimeout(() => { setSettingsClosing(false); setSkinSettingsOpen(false) }, 150)
  }

  const handleCapeSelect = async (capeId: string) => {
    if (!invoke) return
    try {
      await invoke<void>("equip_cape", { capeId })
      setActiveCape(capeId)
    } catch (err) { setError(`Failed to equip cape: ${err}`) }
  }

  const handleCapeRemove = async () => {
    if (!invoke) return
    try {
      await invoke<void>("remove_cape")
      setActiveCape(null)
    } catch (err) { setError(`Failed to remove cape: ${err}`) }
  }

  const handleFileSelect = async (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0]
    if (!file || !invoke) return
    const reader = new FileReader()
    reader.onload = async (e) => {
      const base64 = (e.target?.result as string).split(',')[1]
      setUploading(true)
      setError(null)
      try {
        const result = await invoke<{ url: string; variant: string }>("upload_skin", { skinData: base64, variant: skinVariant })
        if (result && result.url) {
          const match = result.url.match(/texture\/([a-f0-9]+)/)
          if (match) { setCurrentSkinHash(match[1]) }
          const variant = result.variant === "slim" ? "slim" : "classic"
          setSkinVariant(variant)
          if (activeAccount) saveCache<PersistedSkinCache>(SKIN_CACHE_KEY, { uuid: activeAccount.uuid, url: result.url, variant, timestamp: Date.now() })
          await addToRecentSkins(result.url, variant)
        } else {
          setTimeout(() => loadUserSkin(false), 2000)
        }
        setError(null)
      } catch (err) { setError(`Upload failed: ${err}`) } finally { setUploading(false) }
    }
    reader.readAsDataURL(file)
  }

  const handleReset = async () => {
    if (!invoke) return
    setResetting(true)
    setError(null)
    try {
      await invoke<void>("reset_skin")
      sessionStorage.removeItem(SKIN_CACHE_KEY)
      setTimeout(() => loadUserSkin(false), 2000)
    } catch (err) { setError(`Reset failed: ${err}`) } finally { setResetting(false) }
  }

  const handleRecentSkinSelect = async (skin: RecentSkin) => {
    if (!invoke) return
    setUploading(true)
    setError(null)
    try {
      const response = await fetch(skin.url)
      const blob = await response.blob()
      const base64 = await new Promise<string>((resolve, reject) => {
        const reader = new FileReader()
        reader.onload = () => resolve((reader.result as string).split(',')[1])
        reader.onerror = reject
        reader.readAsDataURL(blob)
      })
      const result = await invoke<{ url: string; variant: string }>("upload_skin", { skinData: base64, variant: skin.variant })
      if (result && result.url) {
        const match = result.url.match(/texture\/([a-f0-9]+)/)
        if (match) { setCurrentSkinHash(match[1]) }
        const variant = result.variant === "slim" ? "slim" : "classic"
        setSkinVariant(variant)
        if (activeAccount) saveCache<PersistedSkinCache>(SKIN_CACHE_KEY, { uuid: activeAccount.uuid, url: result.url, variant, timestamp: Date.now() })
      }
      await addToRecentSkins(skin.url, skin.variant)
      setError(null)
    } catch (err) { setError(`Failed to apply skin: ${err}`) } finally { setUploading(false) }
  }

  const getSkinRenderUrl = () => {
    if (!currentSkinHash) return null
    const params: string[] = []
    if (skinVariant === "slim") params.push("alex")
    if (showBack) params.push("y=200")
    const qs = params.length > 0 ? `?${params.join("&")}` : ""
    return `https://renders.stellarmc.gg/full/${currentSkinHash}${qs}`
  }

  if (!isAuthenticated) {
    return (
      <div className="p-8 space-y-4">
        <div className="max-w-7xl mx-auto">
          <div className="mb-6">
            <h1 className="text-2xl font-semibold text-[var(--text-primary)] tracking-tight">Sign In</h1>
          </div>
          <div className="flex flex-col items-center justify-center min-h-[calc(100vh-300px)]">
            <User size={64} className="text-[#4572e3] mb-4" strokeWidth={1.5} />
            <h3 className="text-lg font-semibold text-[var(--text-primary)] mb-1">Sign In Required</h3>
            <p className="text-sm text-[var(--text-muted)]">Please sign in with your Microsoft account to manage your skin</p>
          </div>
        </div>
      </div>
    )
  }

  return (
    <div className="p-8 space-y-4">
      <div className="max-w-7xl mx-auto">
        <div className="flex items-center justify-between mb-6">
          <div>
            <h1 className="text-2xl font-semibold text-[var(--text-primary)] tracking-tight">{activeAccount?.username ?? "Skins"}</h1>
          </div>
          <button onClick={() => setSkinSettingsOpen(true)} className="p-2 bg-[var(--bg-tertiary)] hover:bg-[var(--bg-hover)] text-[var(--text-primary)] rounded-md transition-all cursor-pointer">
            <Settings size={24} />
          </button>
        </div>

        <div className="flex gap-32 items-center justify-center">
          <div className="flex-shrink-0 self-start mt-8">
            <div className="flex flex-col items-center relative">
              <button onClick={() => setShowBack(prev => !prev)} className="absolute top-0 -right-8 z-10 p-2 bg-[var(--bg-tertiary)] hover:bg-[var(--bg-hover)] text-[var(--text-primary)] rounded-md transition-all cursor-pointer">
                <Rotate3d size={20} />
              </button>
              <div className="rounded-md overflow-hidden p-4">
                <div className="w-[270px] h-[438px] flex items-center justify-center">
                  {loading && (
                    <div className="text-center">
                      <Loader2 size={32} className="animate-spin text-[#3b82f6] mx-auto mb-3" />
                      <p className="text-sm text-[var(--text-muted)]">Loading skin...</p>
                    </div>
                  )}
                  {!loading && currentSkinHash && (
                    <img src={getSkinRenderUrl() || ''} alt="Minecraft skin render" className="w-full h-full object-contain" style={{ imageRendering: 'pixelated' }} />
                  )}
                  {!loading && !currentSkinHash && (
                    <p className="text-sm text-[var(--text-muted)]">No skin loaded</p>
                  )}
                </div>
              </div>
            </div>
          </div>

          <div className="flex-1 max-w-sm space-y-6">
            <div>
              <h3 className="text-lg font-semibold text-[var(--text-primary)] mb-2">Upload Skin</h3>
              <input ref={fileInputRef} type="file" accept="image/png" onChange={handleFileSelect} className="hidden" />
              <button onClick={() => fileInputRef.current?.click()} disabled={uploading || loading} className="w-full aspect-[3/1] bg-[var(--bg-tertiary)] hover:bg-[var(--bg-hover)] border-2 border-dashed border-[var(--bg-hover-strong)] rounded-lg flex items-center justify-center gap-2 transition-all cursor-pointer disabled:opacity-50 disabled:cursor-not-allowed">
                {uploading ? <Loader2 size={20} className="animate-spin text-[var(--text-muted)]" /> : <><Upload size={20} className="text-[var(--text-muted)]" /><span className="text-sm text-[var(--text-muted)]">Upload Skin</span></>}
              </button>
            </div>

            {recentSkins.length > 0 && (
              <div>
                <h3 className="text-lg font-semibold text-[var(--text-primary)] mb-2">Recent Skins</h3>
                <div className="grid grid-cols-3 gap-3">
                  {recentSkins.map((skin, index) => {
                    const match = skin.url.match(/texture\/([a-f0-9]+)/)
                    const hash = match ? match[1] : null
                    const renderUrl = hash ? `https://renders.stellarmc.gg/bust/${hash}${skin.variant === 'slim' ? '?slim' : ''}` : skin.url
                    return (
                      <button key={`${skin.url}-${index}`} onClick={() => handleRecentSkinSelect(skin)} disabled={uploading} className="aspect-square bg-[var(--bg-tertiary)] hover:bg-[var(--bg-hover)] rounded-lg transition-all disabled:opacity-50 disabled:cursor-not-allowed cursor-pointer overflow-hidden">
                        <img src={renderUrl} alt="Recent skin" className="w-full h-full object-cover" style={{ imageRendering: 'pixelated' }} />
                      </button>
                    )
                  })}
                </div>
              </div>
            )}

            {error && (
              <div className="bg-[var(--bg-tertiary)] rounded-md p-4">
                <p className="text-xs text-red-400 leading-relaxed">{error}</p>
              </div>
            )}
          </div>
        </div>
      </div>

      {(skinSettingsOpen || settingsClosing) && (
        <div className={`fixed inset-0 bg-black/60 flex items-center justify-center z-50 modal-backdrop ${settingsClosing ? 'closing' : ''}`} onClick={handleCloseSettings}>
          <div className={`bg-[var(--bg-elevated)] rounded-lg p-5 max-w-lg w-full mx-4 max-h-[85vh] overflow-y-auto modal-content ${settingsClosing ? 'closing' : ''}`} onClick={(e) => e.stopPropagation()}>
            <div className="flex items-center justify-between mb-5">
              <h2 className="text-lg font-semibold text-[var(--text-primary)]">Skin Settings</h2>
              <button onClick={handleCloseSettings} className="p-1 hover:bg-[var(--bg-tertiary)] rounded-md transition-colors cursor-pointer">
                <X size={18} className="text-[var(--text-muted)]" />
              </button>
            </div>
            <div className="space-y-5">
              <div>
                <label className="text-sm font-medium text-[var(--text-muted)] mb-2 block">Model</label>
                <div className="flex gap-2">
                  <button onClick={() => setSkinVariant("classic")} className={`flex-1 px-4 py-2 rounded-md text-sm font-medium transition-all cursor-pointer ${skinVariant === "classic" ? "bg-[#4572e3] text-white" : "bg-[var(--bg-secondary)] text-[var(--text-muted)] hover:bg-[var(--bg-hover)] hover:text-[var(--text-primary)]"}`}>
                    Classic
                  </button>
                  <button onClick={() => setSkinVariant("slim")} className={`flex-1 px-4 py-2 rounded-md text-sm font-medium transition-all cursor-pointer ${skinVariant === "slim" ? "bg-[#4572e3] text-white" : "bg-[var(--bg-secondary)] text-[var(--text-muted)] hover:bg-[var(--bg-hover)] hover:text-[var(--text-primary)]"}`}>
                    Slim
                  </button>
                </div>
              </div>
              <div>
                <label className="text-sm font-medium text-[var(--text-muted)] mb-2 block">Capes</label>
                {loadingCapes ? (
                  <div className="flex items-center justify-center py-6">
                    <Loader2 size={20} className="animate-spin text-[var(--text-muted)]" />
                  </div>
                ) : capes.length > 0 ? (
                  <div className="grid grid-cols-6 gap-2">
                    {capes.map((cape) => (
                      <button
                        key={cape.id}
                        onClick={() => handleCapeSelect(cape.id)}
                        className={`group aspect-[5/8] bg-[var(--bg-secondary)] hover:bg-[var(--bg-hover-strong)] rounded-md overflow-hidden flex items-center justify-center transition-all cursor-pointer relative ${activeCape === cape.id ? "ring-2 ring-[var(--accent-primary)]" : ""}`}
                      >
                        <img src={`/capes/${getCapeImageName(cape.alias)}.webp`} alt={cape.alias} className="w-full h-full object-contain" style={{ imageRendering: 'pixelated' }} onError={(e) => { e.currentTarget.src = '/logo.png' }} />
                        <div className="absolute inset-0 bg-black/0 group-hover:bg-black/20 transition-all rounded-md pointer-events-none" />
                      </button>
                    ))}
                  </div>
                ) : (
                  <p className="text-sm text-[var(--text-muted)]">No capes available</p>
                )}
              </div>
              <div className="flex gap-2">
                {activeCape && (
                  <button onClick={handleCapeRemove} className="flex-1 px-4 py-2 bg-[var(--bg-secondary)] hover:bg-[var(--bg-hover)] text-[var(--text-primary)] rounded-md text-sm font-medium transition-all cursor-pointer">
                    Remove Cape
                  </button>
                )}
                <button onClick={handleReset} disabled={resetting || loading} className={`${activeCape ? 'flex-1' : 'w-full'} px-4 py-2 bg-[var(--bg-secondary)] hover:bg-[var(--bg-hover)] disabled:opacity-50 disabled:cursor-not-allowed text-[var(--text-primary)] rounded-md text-sm font-medium transition-all cursor-pointer`}>
                  {resetting ? "Resetting..." : "Reset to Default"}
                </button>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  )
}
