// src/frontend/tabs/SkinsTab.tsx
import { useEffect, useRef, useState } from "react"
import { Upload, RotateCcw, Loader2, User, X, RotateCw } from "lucide-react"

interface SkinsTabProps {
  activeAccount?: { uuid: string; username: string } | null
  isAuthenticated?: boolean
  invoke?: (command: string, args?: any) => Promise<any>
}

interface CachedSkin {
  url: string
  variant: "classic" | "slim"
  timestamp: number
}

interface RecentSkin {
  url: string
  variant: "classic" | "slim"
  timestamp: number
}

interface Cape {
  id: string
  state: string
  url: string
  alias: string
  icon?: string
}

export function SkinsTab(props: SkinsTabProps) {
  const { activeAccount, isAuthenticated, invoke } = props
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)
  const [uploading, setUploading] = useState(false)
  const [resetting, setResetting] = useState(false)
  const [skinVariant, setSkinVariant] = useState<"classic" | "slim">("classic")
  const [capes, setCapes] = useState<Cape[]>([])
  const [activeCape, setActiveCape] = useState<string | null>(null)
  const [loadingCapes, setLoadingCapes] = useState(false)
  const [recentSkins, setRecentSkins] = useState<RecentSkin[]>([])
  const [currentSkinHash, setCurrentSkinHash] = useState<string | null>(null)
  const [showCape, setShowCape] = useState(true)
  const [capeModalOpen, setCapeModalOpen] = useState(false)
  const [isClosingModal, setIsClosingModal] = useState(false)
  const [showBack, setShowBack] = useState(false)
  const fileInputRef = useRef<HTMLInputElement>(null)
  const skinCacheRef = useRef<Map<string, CachedSkin>>(new Map())
  const CACHE_DURATION = 5 * 60 * 1000 // 5 minutes

  // Load recent skins from persistent storage on mount
  useEffect(() => {
    if (!activeAccount || !invoke) {
      setRecentSkins([])
      return
    }
    
    loadRecentSkins()
  }, [activeAccount, invoke])

  // Load recent skins from Tauri storage
  const loadRecentSkins = async () => {
    if (!activeAccount || !invoke) return
    
    try {
      const result = await invoke("load_recent_skins", { 
        accountUuid: activeAccount.uuid 
      })
      
      if (result && Array.isArray(result)) {
        setRecentSkins(result)
      } else {
        setRecentSkins([])
      }
    } catch (err) {
      console.error("Failed to load recent skins:", err)
      setRecentSkins([])
    }
  }

  // Save a skin to recent skins
  const addToRecentSkins = async (url: string, variant: "classic" | "slim") => {
    if (!activeAccount || !invoke) return
    
    try {
      // Create the new recent skin entry
      const newSkin: RecentSkin = { url, variant, timestamp: Date.now() }
      
      // Update local state optimistically
      setRecentSkins(prev => {
        const filtered = prev.filter(s => s.url !== url)
        return [newSkin, ...filtered].slice(0, 3)
      })
      
      // Save to persistent storage
      await invoke("save_recent_skin", {
        accountUuid: activeAccount.uuid,
        skinUrl: url,
        variant: variant
      })
    } catch (err) {
      console.error("Failed to save recent skin:", err)
    }
  }

  useEffect(() => {
    loadUserSkin()
  }, [activeAccount])

  const getCapeImageName = (alias: string) => {
    const specialCases: Record<string, string> = {
      "follower's": "followers",
      "purple heart": "purple",
      "15th anniversary": "15th"
    }
    
    const lowerAlias = alias.toLowerCase()
    if (specialCases[lowerAlias]) {
      return specialCases[lowerAlias]
    }
    
    return lowerAlias.replace(/\s+/g, '_').replace(/['']/g, '')
  }

  const loadUserSkin = async () => {
    if (!isAuthenticated || !activeAccount || !invoke) {
      setLoading(false)
      setError("Please sign in to view your skin")
      return
    }

    try {
      setLoading(true)
      setError(null)
      
      const cacheKey = activeAccount.uuid
      const cached = skinCacheRef.current.get(cacheKey)
      const now = Date.now()
      
      if (cached && (now - cached.timestamp) < CACHE_DURATION) {
        const match = cached.url.match(/texture\/([a-f0-9]+)/)
        if (match) {
          setCurrentSkinHash(match[1])
        }
        setSkinVariant(cached.variant)
        setLoading(false)
        loadCapes()
        return
      }
      
      const skinData = await invoke("get_current_skin")
      
      if (skinData && skinData.url) {
        const variant = skinData.variant === "slim" ? "slim" : "classic"
        
        const match = skinData.url.match(/texture\/([a-f0-9]+)/)
        if (match) {
          setCurrentSkinHash(match[1])
        }
        
        setSkinVariant(variant)
        
        skinCacheRef.current.set(cacheKey, {
          url: skinData.url,
          variant: variant,
          timestamp: now
        })
        
        setLoading(false)
        loadCapes()
      } else {
        setCurrentSkinHash(null)
        setLoading(false)
        loadCapes()
      }
    } catch (err) {
      console.error("Failed to load skin:", err)
      setError(`Failed to load skin: ${err}`)
      setLoading(false)
      setCurrentSkinHash(null)
    }
  }

  const loadCapes = async () => {
    if (!invoke || !isAuthenticated) return

    try {
      setLoadingCapes(true)
      const capeData = await invoke("get_user_capes")
      
      if (capeData && capeData.capes) {
        setCapes(capeData.capes)
        const active = capeData.capes.find((cape: Cape) => cape.state === "ACTIVE")
        const activeCapeId = active?.id || null
        setActiveCape(activeCapeId)
        setShowCape(!!activeCapeId)
      }
    } catch (err) {
      console.error("Failed to load capes:", err)
    } finally {
      setLoadingCapes(false)
    }
  }

  const handleCapeSelect = async (capeId: string) => {
    if (!invoke) return

    try {
      await invoke("equip_cape", { capeId })
      setActiveCape(capeId)
      setShowCape(true)
      handleCloseCapeModal()
    } catch (err) {
      console.error("Failed to equip cape:", err)
      setError(`Failed to equip cape: ${err}`)
    }
  }

  const handleCapeRemove = async () => {
    if (!invoke) return
    
    try {
      await invoke("remove_cape")
      setActiveCape(null)
      setShowCape(false)
      handleCloseCapeModal()
    } catch (err) {
      console.error("Failed to remove cape:", err)
      setError(`Failed to remove cape: ${err}`)
    }
  }

  const handleCloseCapeModal = () => {
    setIsClosingModal(true)
    setTimeout(() => {
      setIsClosingModal(false)
      setCapeModalOpen(false)
    }, 150)
  }

  const handleRotate = () => {
    setShowBack((prev) => !prev)
  }

  const handleFileSelect = async (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0]
    if (!file || !invoke) return

    const reader = new FileReader()
    reader.onload = async (e) => {
      const base64Data = e.target?.result as string
      const base64 = base64Data.split(',')[1]

      setUploading(true)
      setError(null)

      try {
        await invoke("upload_skin", {
          skinData: base64,
          variant: skinVariant
        })

        if (activeAccount) {
          skinCacheRef.current.delete(activeAccount.uuid)
        }

        await loadUserSkin()
        
        // Add to recent skins after successful upload
        const skinData = await invoke("get_current_skin")
        if (skinData && skinData.url) {
          await addToRecentSkins(skinData.url, skinData.variant === "slim" ? "slim" : "classic")
        }
        
        setError(null)
      } catch (err) {
        setError(`Upload failed: ${err}`)
      } finally {
        setUploading(false)
      }
    }

    reader.readAsDataURL(file)
  }

  const handleReset = async () => {
    if (!invoke) return

    setResetting(true)
    setError(null)

    try {
      await invoke("reset_skin")
      
      if (activeAccount) {
        skinCacheRef.current.delete(activeAccount.uuid)
      }
      
      await loadUserSkin()
    } catch (err) {
      setError(`Reset failed: ${err}`)
    } finally {
      setResetting(false)
    }
  }

  const handleRecentSkinSelect = async (skin: RecentSkin) => {
    if (!invoke) return

    setUploading(true)
    setError(null)

    try {
      // Download the skin image
      const response = await fetch(skin.url)
      const blob = await response.blob()
      
      // Convert to base64
      const base64 = await new Promise<string>((resolve, reject) => {
        const reader = new FileReader()
        reader.onload = () => {
          const result = reader.result as string
          resolve(result.split(',')[1])
        }
        reader.onerror = reject
        reader.readAsDataURL(blob)
      })

      // Upload the skin
      await invoke("upload_skin", {
        skinData: base64,
        variant: skin.variant
      })

      if (activeAccount) {
        skinCacheRef.current.delete(activeAccount.uuid)
      }

      await loadUserSkin()
      
      // Move to top of recent skins
      await addToRecentSkins(skin.url, skin.variant)
      
      setError(null)
    } catch (err) {
      setError(`Failed to apply skin: ${err}`)
    } finally {
      setUploading(false)
    }
  }

  const getSkinRenderUrl = () => {
    if (!activeAccount) return null
    
    const variant = skinVariant === "slim" ? "slim" : "wide"
    const capeParam = showCape && activeCape ? "" : "&no=cape"
    const angleParam = showBack ? "&y=180" : ""

    return `https://vzge.me/full/512/${activeAccount.uuid}?${variant}${capeParam}${angleParam}`
  }

  if (!isAuthenticated) {
    return (
      <div className="p-6 space-y-4">
        <div className="max-w-7xl mx-auto">
          <div className="mb-6">
            <h1 className="text-2xl font-semibold text-[#e6e6e6] tracking-tight">Skins</h1>
            <p className="text-sm text-[#7d8590] mt-0.5">Manage your Minecraft skin</p>
          </div>
          
          <div className="flex flex-col items-center justify-center min-h-[calc(100vh-300px)]">
            <User size={64} className="text-[#4572e3] mb-4" strokeWidth={1.5} />
            <h3 className="text-lg font-semibold text-[#e6e6e6] mb-1">Sign In Required</h3>
            <p className="text-sm text-[#7d8590]">Please sign in with your Microsoft account to manage your skin</p>
          </div>
        </div>
      </div>
    )
  }

  return (
    <div className="p-6 space-y-4">
      <style>{`
        @keyframes fadeIn {
          from { opacity: 0; }
          to { opacity: 1; }
        }
        @keyframes fadeOut {
          from { opacity: 1; }
          to { opacity: 0; }
        }
        @keyframes scaleIn {
          from { 
            opacity: 0;
            transform: scale(0.95);
          }
          to { 
            opacity: 1;
            transform: scale(1);
          }
        }
        @keyframes scaleOut {
          from { 
            opacity: 1;
            transform: scale(1);
          }
          to { 
            opacity: 0;
            transform: scale(0.95);
          }
        }
        .modal-backdrop {
          animation: fadeIn 0.15s ease-out forwards;
        }
        .modal-backdrop.closing {
          animation: fadeOut 0.15s ease-in forwards;
        }
        .modal-content {
          animation: scaleIn 0.15s ease-out forwards;
        }
        .modal-content.closing {
          animation: scaleOut 0.15s ease-in forwards;
        }

        .blur-border {
          position: relative;
        }

        .blur-border::before {
          content: '';
          position: absolute;
          inset: 0;
          border-radius: inherit;
          padding: 2px;
          background: linear-gradient(
            180deg,
            rgba(255, 255, 255, 0.08),
            rgba(255, 255, 255, 0.04)
          );
          -webkit-mask: linear-gradient(#fff 0 0) content-box, linear-gradient(#fff 0 0);
          -webkit-mask-composite: xor;
          mask-composite: exclude;
          pointer-events: none;
          backdrop-filter: blur(8px);
          z-index: 10;
        }
      `}</style>
      <div className="max-w-7xl mx-auto">
        <div className="flex items-center justify-between mb-6">
          <div>
            <h1 className="text-2xl font-semibold text-[#e6e6e6] tracking-tight">Skins</h1>
            <p className="text-sm text-[#7d8590] mt-0.5">
              {activeAccount ? `Viewing skin for ${activeAccount.username}` : "Manage your Minecraft skin"}
            </p>
          </div>
        </div>

        <div className="flex gap-24 items-center justify-center">
          {/* Skin Viewer */}
          <div className="flex-shrink-0 self-start mt-8">
            <div className="flex flex-col items-center">
              <div className="rounded-md overflow-hidden relative bg-[#181a1f] p-4">
                {loading && (
                  <div className="w-[250px] h-[406px] flex items-center justify-center bg-[#181a1f] rounded-md">
                    <div className="text-center">
                      <Loader2 size={32} className="animate-spin text-[#16a34a] mx-auto mb-3" />
                      <p className="text-sm text-[#7d8590]">Loading skin...</p>
                    </div>
                  </div>
                )}
                
                {!loading && currentSkinHash && (
                  <img
                    src={getSkinRenderUrl() || ''}
                    alt="Minecraft skin render"
                    className="w-[250px] h-[406px]"
                    style={{ imageRendering: 'pixelated' }}
                  />
                )}
                
                {!loading && !currentSkinHash && (
                  <div className="w-[250px] h-[406px] flex items-center justify-center">
                    <p className="text-sm text-[#7d8590]">No skin loaded</p>
                  </div>
                )}
              </div>

              {/* Capes Button */}
              <button
                onClick={() => setCapeModalOpen(true)}
                className="mt-3 px-4 py-2 bg-[#22252b] hover:bg-[#2a2d35] text-[#e6e6e6] rounded-md text-sm font-medium transition-all cursor-pointer"
              >
                Manage Capes {capes.length > 0 && `(${capes.length})`}
              </button>
            </div>
          </div>

          {/* Controls Panel */}
          <div className="flex-1 max-w-sm space-y-4">
            <div className="blur-border bg-[#22252b] rounded-md p-5">
              <div className="flex items-center justify-between mb-4">
                <h3 className="text-base font-semibold text-[#e6e6e6]">Skin Model</h3>
                <button
                  onClick={handleRotate}
                  className="p-2 hover:bg-[#1f2128] text-[#e6e6e6] rounded-md transition-all cursor-pointer"
                >
                  <RotateCw size={16} />
                </button>
              </div>
              
              <div className="flex gap-2 mb-6">
                <button
                  onClick={() => setSkinVariant("classic")}
                  className={`flex-1 px-4 py-2.5 rounded-md text-sm font-medium transition-all cursor-pointer ${
                    skinVariant === "classic"
                      ? "bg-[#4572e3] text-white"
                      : "bg-[#181a1f] text-[#7d8590] hover:bg-[#1f2128] hover:text-[#e6e6e6]"
                  }`}
                >
                  Classic
                </button>
                <button
                  onClick={() => setSkinVariant("slim")}
                  className={`flex-1 px-4 py-2.5 rounded-md text-sm font-medium transition-all cursor-pointer ${
                    skinVariant === "slim"
                      ? "bg-[#4572e3] text-white"
                      : "bg-[#181a1f] text-[#7d8590] hover:bg-[#1f2128] hover:text-[#e6e6e6]"
                  }`}
                >
                  Slim
                </button>
              </div>

              <div className="space-y-3">
                <input
                  ref={fileInputRef}
                  type="file"
                  accept="image/png"
                  onChange={handleFileSelect}
                  className="hidden"
                />
                
                <button
                  onClick={() => fileInputRef.current?.click()}
                  disabled={uploading || loading}
                  className="w-full flex items-center justify-center gap-2 px-4 py-3 bg-[#16a34a] hover:bg-[#15803d] disabled:opacity-50 disabled:cursor-not-allowed text-white rounded-md font-medium text-sm transition-all cursor-pointer"
                >
                  {uploading ? (
                    <>
                      <Loader2 size={16} className="animate-spin" />
                      <span>Uploading...</span>
                    </>
                  ) : (
                    <>
                      <Upload size={16} />
                      <span>Upload New Skin</span>
                    </>
                  )}
                </button>
                
                <button
                  onClick={handleReset}
                  disabled={resetting || loading}
                  className="w-full flex items-center justify-center gap-2 px-4 py-3 bg-[#181a1f] hover:bg-[#1f2128] disabled:opacity-50 disabled:cursor-not-allowed text-[#e6e6e6] rounded-md font-medium text-sm transition-all cursor-pointer"
                >
                  {resetting ? (
                    <>
                      <Loader2 size={16} className="animate-spin" />
                      <span>Resetting...</span>
                    </>
                  ) : (
                    <>
                      <RotateCcw size={16} />
                      <span>Reset to Default</span>
                    </>
                  )}
                </button>
              </div>
            </div>

            {/* Recent Skins */}
            {recentSkins.length > 0 && (
              <div className="blur-border bg-[#22252b] rounded-md p-5">
                <div className="flex items-center gap-2 mb-4">
                  <h3 className="text-base font-semibold text-[#e6e6e6]">Recent Skins</h3>
                </div>
                
                <div className="flex gap-3">
                  {recentSkins.map((skin, index) => {
                    // Extract texture hash from URL
                    const match = skin.url.match(/texture\/([a-f0-9]+)/)
                    const hash = match ? match[1] : null
                    // Use bust render from VZGE
                    const renderUrl = hash 
                      ? `https://vzge.me/bust/128/${hash}${skin.variant === 'slim' ? '?slim' : '?wide'}`
                      : skin.url
                    
                    return (
                      <button
                        key={`${skin.url}-${index}`}
                        onClick={() => handleRecentSkinSelect(skin)}
                        disabled={uploading}
                        className="bg-[#181a1f] rounded-md hover:ring-2 hover:ring-[#4572e3] transition-all disabled:opacity-50 disabled:cursor-not-allowed cursor-pointer overflow-hidden"
                      >
                        <img
                          src={renderUrl}
                          alt="Recent skin"
                          className="w-20 h-20"
                          style={{ imageRendering: 'pixelated' }}
                        />
                      </button>
                    )
                  })}
                </div>
              </div>
            )}
            
            {error && (
              <div className="blur-border bg-[#22252b] rounded-md p-4">
                <p className="text-xs text-red-400 leading-relaxed">{error}</p>
              </div>
            )}
          </div>
        </div>
      </div>

      {/* Cape Modal */}
      {capeModalOpen && (
        <div 
          className={`fixed inset-0 bg-black/60 backdrop-blur-sm flex items-center justify-center z-50 modal-backdrop ${isClosingModal ? 'closing' : ''}`}
          onClick={handleCloseCapeModal}
        >
          <div 
            className={`blur-border bg-[#181a1f] rounded-lg p-6 max-w-2xl w-full mx-4 max-h-[80vh] overflow-y-auto modal-content ${isClosingModal ? 'closing' : ''}`}
            onClick={(e) => e.stopPropagation()}
          >
            <div className="flex items-center justify-between mb-6">
              <h2 className="text-xl font-semibold text-[#e6e6e6]">Manage Capes</h2>
              <button
                onClick={handleCloseCapeModal}
                className="p-1 hover:bg-[#22252b] rounded-md transition-colors cursor-pointer"
              >
                <X size={20} className="text-[#7d8590]" />
              </button>
            </div>

            {loadingCapes ? (
              <div className="flex items-center justify-center py-12">
                <Loader2 size={32} className="animate-spin text-[#16a34a]" />
              </div>
            ) : capes.length > 0 ? (
              <div className="space-y-4">
                <div className="grid grid-cols-5 gap-3">
                  {capes.map((cape) => (
                    <button
                      key={cape.id}
                      onClick={() => handleCapeSelect(cape.id)}
                      className={`aspect-[5/8] bg-[#181a1f] rounded-md overflow-hidden flex flex-col items-center justify-center transition-all cursor-pointer hover:ring-2 hover:ring-[#4572e3] ${
                        activeCape === cape.id
                          ? "ring-2 ring-[#4572e3]"
                          : ""
                      }`}
                      title={cape.alias}
                    >
                      <img 
                        src={`/capes/${getCapeImageName(cape.alias)}.png`}
                        alt={cape.alias}
                        className="w-full h-full object-contain"
                        style={{ imageRendering: 'pixelated' }}
                        onError={(e) => {
                          e.currentTarget.src = '/logo.png'
                        }}
                      />
                    </button>
                  ))}
                </div>
                
                {activeCape && (
                  <button
                    onClick={handleCapeRemove}
                    className="w-full px-4 py-3 bg-[#22252b] hover:bg-[#2a2d35] text-[#e6e6e6] rounded-md text-sm font-medium transition-all cursor-pointer"
                  >
                    Remove Cape
                  </button>
                )}
              </div>
            ) : (
              <div className="text-center py-12">
                <p className="text-sm text-[#7d8590]">No capes available</p>
              </div>
            )}
          </div>
        </div>
      )}
    </div>
  )
}

// frontend/features/skins/SkinsTab.svelte
<script lang="ts">
  import { invoke } from "@tauri-apps/api/core"
  import { Upload, Loader2, User, RotateCcw, Save, Plane, RectangleVertical } from "lucide-svelte"
  import * as skinview3d from "skinview3d"
  import type { RecentSkin, Cape } from "../../types"
  import { storeGet, storeSet, storeRemove } from "../../lib/store"
  import { store } from "../../lib/launcherStore.svelte"
  import { untrack } from "svelte"

  const SKIN_CACHE_KEY = "octane_skin_cache"
  const CAPE_CACHE_KEY = "octane_cape_cache"
  const CACHE_DURATION = 15 * 60 * 1000
  const MIN_FETCH_INTERVAL = 10 * 1000

  function loadCache<T>(key: string): Promise<T | null> {
    return storeGet<T>(key).then(v => v ?? null)
  }

  function saveCache<T>(key: string, data: T) {
    return storeSet(key, data)
  }

  const canFetch = (last: number) => Date.now() - last >= MIN_FETCH_INTERVAL

  type PersistedSkinCache = { uuid: string; url: string; variant: string; timestamp: number }
  type PersistedCapeCache = { uuid: string; capes: Cape[]; activeCapeId: string | null; timestamp: number }

  let loading = $state(true)
  let error = $state<string | null>(null)
  let uploading = $state(false)
  let skinVariant = $state<"classic" | "slim">("classic")
  let capes = $state<Cape[]>([])
  let activeCape = $state<string | null>(null)
  let loadingCapes = $state(false)
  let showElytra = $state(false)
  let recentSkins = $state<RecentSkin[]>([])
  let currentSkinUrl = $state<string | null>(null)
  let containerSize = $state({ width: 800, height: 600 })
  let hasPendingChanges = $state(false)
  let saving = $state(false)

  let containerEl: HTMLDivElement | undefined = $state()
  let canvasEl: HTMLCanvasElement | undefined = $state()
  let fileInputEl: HTMLInputElement | undefined = $state()

  let viewer = $state<skinview3d.SkinViewer | null>(null)
  let skinResetTimeout: ReturnType<typeof setTimeout> | undefined
  let dragState = { active: false, startX: 0, startRot: 0.3 }
  let lastProfileFetch: Record<string, number> = {}
  let lastCapeFetch: Record<string, number> = {}
  let originalState = { skinUrl: null as string | null, variant: 'classic' as 'classic' | 'slim', activeCape: null as string | null }
  let pendingSkinOp: { type: 'upload'; base64: string; variant: 'classic' | 'slim' } | { type: 'recent'; url: string; variant: 'classic' | 'slim' } | { type: 'reset' } | null = null
  let pendingCapeOp: { type: 'select'; capeId: string } | { type: 'remove' } | null = null
  let loadUserSkinFn: (forceRefresh?: boolean) => Promise<void> = async () => {}

  let prevSkinUrl: string | undefined
  $effect(() => {
    store.activeAccount
    untrack(() => {
      if (prevSkinUrl?.startsWith('blob:')) URL.revokeObjectURL(prevSkinUrl)
      prevSkinUrl = currentSkinUrl ?? undefined
      pendingSkinOp = null
      pendingCapeOp = null
      hasPendingChanges = false
    })
  })

  $effect(() => {
    if (!store.activeAccount) { recentSkins = []; return }
    loadRecentSkins()
  })

  $effect(() => { loadUserSkin() })

  async function loadRecentSkins() {
    if (!store.activeAccount) return
    try {
      const result = await invoke<RecentSkin[]>("load_recent_skins", { accountUuid: store.activeAccount.uuid })
      recentSkins = Array.isArray(result) ? result : []
    } catch { recentSkins = [] }
  }

  async function addToRecentSkins(url: string, variant: "classic" | "slim") {
    if (!store.activeAccount) return
    recentSkins = [{ url, variant, timestamp: Date.now() }, ...recentSkins.filter(s => s.url !== url)].slice(0, 3)
    try { await invoke<void>("save_recent_skin", { accountUuid: store.activeAccount.uuid, skinUrl: url, variant }) }
    catch { console.error("Failed to save recent skin") }
  }

  function applyUploadedSkin(result: { url: string; variant: string }): "classic" | "slim" | null {
    if (!result?.url) return null
    const variant: "classic" | "slim" = result.variant === "slim" ? "slim" : "classic"
    skinVariant = variant
    currentSkinUrl = result.url
    if (store.activeAccount) {
      saveCache<PersistedSkinCache>(SKIN_CACHE_KEY, {
        uuid: store.activeAccount.uuid, url: result.url, variant, timestamp: Date.now(),
      })
    }
    return variant
  }

  const CAPE_TEX_W = 64
  const CAPE_FRONT = { x: 1, y: 1, w: 10, h: 16 }
  const CAPE_THUMB_SCALE = 2

  function normalizeCapeUrl(url: string) { return url.replace("http://", "https://") }

  async function loadUserSkin(forceRefresh = false) {
    if (!store.isAuthenticated || !store.activeAccount) {
      loading = false; error = "Please sign in to view your skin"; return
    }
    try {
      loading = true; error = null
      const now = Date.now()
      const persisted = await loadCache<PersistedSkinCache>(SKIN_CACHE_KEY)
      const cacheValid =
        persisted && persisted.uuid === store.activeAccount.uuid && (now - persisted.timestamp) < CACHE_DURATION

      const applyCached = () => {
        if (!cacheValid) return
        currentSkinUrl = persisted!.url
        skinVariant = persisted!.variant as "classic" | "slim"
        originalState = { ...originalState, skinUrl: persisted!.url, variant: persisted!.variant as "classic" | "slim" }
      }

      if (!forceRefresh && cacheValid) { applyCached(); loading = false; loadCapes(); return }
      if (!canFetch(lastProfileFetch[store.activeAccount.uuid] ?? 0)) { applyCached(); loading = false; loadCapes(); return }

      lastProfileFetch[store.activeAccount.uuid] = now
      const skinData = await invoke<{ url: string; variant: string }>("get_current_skin")
      if (skinData?.url) {
        const variant = skinData.variant === "slim" ? "slim" : "classic"
        currentSkinUrl = skinData.url
        skinVariant = variant
        originalState = { ...originalState, skinUrl: skinData.url, variant }
        await saveCache<PersistedSkinCache>(SKIN_CACHE_KEY, {
          uuid: store.activeAccount.uuid, url: skinData.url, variant, timestamp: now,
        })
      } else {
        currentSkinUrl = null
      }
      loading = false; loadCapes()
    } catch (err: unknown) {
      if (typeof err === "string" && err.includes("429")) {
        error = "Rate limited — please wait before refreshing."
        const persisted = await loadCache<PersistedSkinCache>(SKIN_CACHE_KEY)
        if (persisted && persisted.uuid === store.activeAccount?.uuid) {
          currentSkinUrl = persisted.url
          skinVariant = persisted.variant as "classic" | "slim"
          originalState = { ...originalState, skinUrl: persisted.url, variant: persisted.variant as "classic" | "slim" }
        }
      } else {
        error = `Failed to load skin: ${String(err)}`; currentSkinUrl = null
      }
      loading = false
    }
  }
  loadUserSkinFn = loadUserSkin

  async function loadCapes() {
    if (!store.isAuthenticated || !store.activeAccount) return
    const now = Date.now()
    const persisted = await loadCache<PersistedCapeCache>(CAPE_CACHE_KEY)
    const cacheValid =
      persisted && persisted.uuid === store.activeAccount.uuid && (now - persisted.timestamp) < CACHE_DURATION
    if (cacheValid) {
      capes = persisted!.capes.map(c => ({ ...c, url: normalizeCapeUrl(c.url) })); activeCape = persisted!.activeCapeId
      originalState = { ...originalState, activeCape: persisted!.activeCapeId }
      return
    }

    capes = []; activeCape = null
    if (!canFetch(lastCapeFetch[store.activeAccount.uuid] ?? 0)) return
    try {
      loadingCapes = true
      lastCapeFetch[store.activeAccount.uuid] = now
      const capeData = await invoke<{ capes: Cape[] }>("get_user_capes")
      if (capeData?.capes) {
        capes = capeData.capes.map(c => ({ ...c, url: normalizeCapeUrl(c.url) }))
        const activeId = capeData.capes.find((c: Cape) => c.state === "ACTIVE")?.id ?? null
        activeCape = activeId
        originalState = { ...originalState, activeCape: activeId }
        await saveCache<PersistedCapeCache>(CAPE_CACHE_KEY, {
          uuid: store.activeAccount.uuid, capes: capeData.capes, activeCapeId: activeId, timestamp: now,
        })
      }
    } catch { console.error("Failed to load capes") } finally { loadingCapes = false }
  }

  function handleCapeSelect(capeId: string) {
    activeCape = capeId
    pendingCapeOp = { type: 'select', capeId }
    hasPendingChanges = true
  }

  function handleCapeRemove() {
    activeCape = null
    pendingCapeOp = { type: 'remove' }
    hasPendingChanges = true
  }

  function handleFileSelect(event: Event) {
    const input = event.target as HTMLInputElement
    const file = input.files?.[0]
    if (!file) return
    const localUrl = URL.createObjectURL(file)
    uploading = true
    currentSkinUrl = localUrl
    const reader = new FileReader()
    reader.onload = (e) => {
      const base64 = ((e.target?.result) as string).split(",")[1]
      pendingSkinOp = { type: 'upload', base64, variant: skinVariant }
      hasPendingChanges = true
      uploading = false
    }
    reader.readAsDataURL(file)
  }

  function handleReset() {
    pendingSkinOp = { type: 'reset' }
    hasPendingChanges = true
  }

  function handleRecentSkinSelect(skin: RecentSkin) {
    currentSkinUrl = skin.url
    skinVariant = skin.variant
    pendingSkinOp = { type: 'recent', url: skin.url, variant: skin.variant }
    hasPendingChanges = true
  }

  async function handleSave() {
    saving = true; error = null
    let finalSkinUrl = currentSkinUrl
    let finalVariant = skinVariant
    let finalCape = activeCape
    try {
      const skinOp = pendingSkinOp
      if (skinOp) {
        if (skinOp.type === 'upload') {
          const result = await invoke<{ url: string; variant: string }>('upload_skin', { skinData: skinOp.base64, variant: skinVariant })
          const variant = applyUploadedSkin(result)
          finalSkinUrl = result.url
          finalVariant = variant ?? finalVariant
          if (variant) await addToRecentSkins(result.url, variant)
        } else if (skinOp.type === 'recent') {
          const response = await fetch(skinOp.url)
          const blob = await response.blob()
          const base64 = await new Promise<string>((resolve, reject) => {
            const reader = new FileReader()
            reader.onload = () => resolve((reader.result as string).split(',')[1])
            reader.onerror = reject
            reader.readAsDataURL(blob)
          })
          const result = await invoke<{ url: string; variant: string }>('upload_skin', { skinData: base64, variant: skinVariant })
          const variant = applyUploadedSkin(result)
          finalSkinUrl = result.url
          finalVariant = variant ?? finalVariant
          if (variant) await addToRecentSkins(result.url, variant)
        } else if (skinOp.type === 'reset') {
          await invoke<void>('reset_skin')
          await storeRemove(SKIN_CACHE_KEY)
          skinResetTimeout = setTimeout(() => loadUserSkinFn(false), 2000)
        }
      }

      const capeOp = pendingCapeOp
      if (capeOp) {
        if (capeOp.type === 'select') {
          await invoke<void>('equip_cape', { capeId: capeOp.capeId })
          finalCape = capeOp.capeId
        } else if (capeOp.type === 'remove') {
          await invoke<void>('remove_cape')
          finalCape = null
        }
        if (store.activeAccount) {
          const cached = await loadCache<PersistedCapeCache>(CAPE_CACHE_KEY)
          if (cached?.uuid === store.activeAccount.uuid) {
            await saveCache(CAPE_CACHE_KEY, { ...cached, activeCapeId: finalCape, timestamp: Date.now() })
          }
        }
      }

      if (currentSkinUrl?.startsWith('blob:')) URL.revokeObjectURL(currentSkinUrl)
      originalState = { skinUrl: finalSkinUrl, variant: finalVariant, activeCape: finalCape }
      pendingSkinOp = null
      pendingCapeOp = null
      hasPendingChanges = false
    } catch (err) {
      error = `Save failed: ${err}`
    } finally {
      saving = false
    }
  }

  function handleDiscard() {
    if (currentSkinUrl?.startsWith('blob:')) URL.revokeObjectURL(currentSkinUrl)
    pendingSkinOp = null
    pendingCapeOp = null
    currentSkinUrl = originalState.skinUrl
    skinVariant = originalState.variant
    activeCape = originalState.activeCape
    hasPendingChanges = false
    error = null
  }

  let activeCapeObj = $derived(capes.find(c => c.id === activeCape) ?? null)
  let activeCapeUrl = $derived<string | null>(activeCapeObj?.url ?? null)

  // SkinViewer3D initialization
  $effect(() => {
    const canvas = canvasEl
    const container = containerEl
    if (!canvas || !container) return

    const { width: cw, height: ch } = container.getBoundingClientRect()
    const v = new skinview3d.SkinViewer({ canvas, width: Math.round(cw), height: Math.round(ch) })

    v.renderer.setClearColor(0x000000, 0)
    v.globalLight.intensity = 3.0
    v.cameraLight.intensity = 0.0
    v.animation = new skinview3d.IdleAnimation()
    v.animation.speed = 1
    v.controls.enabled = false
    v.fov = 70
    v.zoom = 0.6
    v.playerObject.rotation.y = 0.3
    v.camera.position.y += 8
    v.camera.lookAt(v.playerObject.position)

    const ro = new ResizeObserver(entries => {
      const { width, height } = entries[0].contentRect
      containerSize = { width: Math.round(width), height: Math.round(height) }
    })
    ro.observe(container)

    viewer = v

    return () => {
      ro.disconnect()
      v.dispose()
      viewer = null
    }
  })

  $effect(() => {
    const v = viewer
    if (!v) return
    const { width, height } = containerSize
    if (width < 1 || height < 1) return
    v.setSize(width, height)
    v.render()
  })

  $effect(() => {
    const v = viewer
    if (!v) return
    if (currentSkinUrl) {
      v.loadSkin(currentSkinUrl, { model: skinVariant === "slim" ? "slim" : "default" })
    } else {
      v.loadSkin(null)
    }
  })

  $effect(() => {
    const v = viewer
    if (!v) return
    if (activeCapeUrl) {
      v.loadCape(activeCapeUrl, showElytra ? { backEquipment: "elytra" } : undefined)
    } else {
      v.loadCape(null)
    }
  })

  $effect(() => {
    const timeout = skinResetTimeout
    return () => clearTimeout(timeout)
  })

  function handlePointerDown(e: PointerEvent) {
    if ((e.target as HTMLElement).closest("button, input")) return
    dragState = {
      active: true,
      startX: e.clientX,
      startRot: viewer?.playerObject.rotation.y ?? 0.3,
    }
    ;(e.currentTarget as HTMLElement)?.setPointerCapture?.(e.pointerId)
  }

  function handlePointerMove(e: PointerEvent) {
    if (!dragState.active || !viewer) return
    const dx = e.clientX - dragState.startX
    viewer.playerObject.rotation.y = dragState.startRot + dx * 0.01
  }

  function handlePointerUp() { dragState.active = false }
  function handlePointerCancel() { dragState.active = false }
</script>

{#if !store.isAuthenticated}
  <div class="p-8 space-y-4">
    <div class="max-w-7xl mx-auto">
      <div class="mb-6">
        <h1 class="text-2xl font-semibold text-[var(--text-primary)] tracking-tight">Sign In</h1>
      </div>
      <div class="flex flex-col items-center justify-center min-h-[calc(100vh-300px)]">
        <User size={64} class="text-[#4572e3] mb-4" strokeWidth={1.5} />
        <h3 class="text-lg font-semibold text-[var(--text-primary)] mb-1">Sign In Required</h3>
        <p class="text-sm text-[var(--text-muted)]">
          Please sign in with your Microsoft account to manage your skin
        </p>
      </div>
    </div>
  </div>
{:else}
  <div
    role="presentation"
    bind:this={containerEl}
    style="position: relative; overflow: hidden; height: 100%; box-sizing: border-box; user-select: none; -webkit-user-select: none;"
    onpointerdown={handlePointerDown}
    onpointermove={handlePointerMove}
    onpointerup={handlePointerUp}
    onpointercancel={handlePointerCancel}
  >
    <div style="position: absolute; inset: 0; z-index: 0; pointer-events: none;">
      <div style="width: 100%; height: 100%; position: relative; overflow: hidden; background-image: url(/skinstab/background.webp); background-size: cover; background-position: center; background-repeat: no-repeat;">
        <div style="position: absolute; inset: 0; background: rgba(0,0,0,0.35); z-index: 1;"></div>
        <div style="position: absolute; inset: 0; z-index: 3; display: flex; flex-direction: column; align-items: center; justify-content: center; pointer-events: none; opacity: {loading ? 1 : 0}; transition: opacity 0.15s;">
          <Loader2 size={32} style="animation: spin 1s linear infinite; color: #3b82f6; margin-bottom: 12px;" />
          <p style="font-size: 14px; color: var(--text-muted); margin: 0;">Loading skin…</p>
        </div>
        <canvas
          bind:this={canvasEl}
          style="display: block; position: relative; z-index: 2; opacity: {loading ? 0 : 1}; transition: opacity 0.2s; width: 100%; height: 100%;"
        ></canvas>
      </div>
    </div>

    <div style="position: relative; z-index: 1; height: 100%; box-sizing: border-box; padding: 32px 32px 88px;">
      <div class="max-w-7xl mx-auto w-full">
        <div class="flex items-center justify-between mb-6">
          <h1 class="text-2xl font-semibold text-[var(--text-primary)] tracking-tight">
            {store.activeAccount?.username ?? "Skins"}
          </h1>
        </div>
      </div>

      {#if error}
        <div style="position: absolute; top: 50%; left: 50%; transform: translate(-50%, -50%); pointer-events: auto;">
          <div class="bg-[var(--bg-tertiary)] rounded-md p-4 max-w-sm w-full">
            <p class="text-xs text-red-400 leading-relaxed text-center">{error}</p>
          </div>
        </div>
      {/if}
    </div>

    <input bind:this={fileInputEl} type="file" accept="image/png" onchange={handleFileSelect} class="hidden" />

    {#snippet tip(text: string)}
      <div class="absolute bottom-[calc(100%+6px)] left-1/2 -translate-x-1/2 px-[7px] py-[3px] rounded border border-[var(--border-color,#333)] bg-[var(--bg-secondary,#1a1a2e)] text-[var(--text-primary,#eee)] text-[11px] whitespace-nowrap pointer-events-none z-[100] hidden group-hover:block">{text}</div>
    {/snippet}

    <div
      role="presentation"
      onpointerdown={(e) => e.stopPropagation()}
      style="position: absolute; bottom: 32px; left: 50%; transform: translateX(-50%); z-index: 10; display: flex; align-items: center; gap: 12px; max-width: calc(100% - 64px); flex-wrap: wrap; justify-content: center;"
    >
      <div style="display: flex; align-items: center; gap: 6px; padding: 6px 10px; border-radius: 12px; background: var(--bg-elevated); backdrop-filter: blur(12px); justify-content: center;">
        <div role="presentation" class="group relative inline-flex">
          <button
            onclick={() => fileInputEl?.click()}
            disabled={uploading || loading}
            class="flex items-center justify-center w-[34px] h-[34px] rounded-md bg-transparent text-[#16a34a] transition-colors shrink-0 enabled:hover:bg-[var(--bg-hover)] enabled:cursor-pointer disabled:cursor-not-allowed disabled:opacity-40"
          >
            {#if uploading}
              <Loader2 size={20} class="animate-spin" />
            {:else}
              <Upload size={20} strokeWidth={2.5} />
            {/if}
          </button>
          {@render tip("Upload skin")}
        </div>

        <div role="presentation" class="group relative inline-flex">
          <button
            onclick={handleReset}
            disabled={loading}
            class="flex items-center justify-center w-[34px] h-[34px] rounded-md bg-transparent text-[var(--text-muted)] transition-colors shrink-0 enabled:hover:bg-[var(--bg-hover)] enabled:cursor-pointer disabled:cursor-not-allowed disabled:opacity-40"
          >
            <RotateCcw size={20} strokeWidth={2.5} />
          </button>
          {@render tip("Reset to default skin")}
        </div>

        <button
          onclick={() => skinVariant = "classic"}
          class="px-[10px] py-[6px] rounded-lg text-[13px] font-semibold tracking-[0.01em] whitespace-nowrap box-border transition-colors cursor-pointer shrink-0 {skinVariant === 'classic' ? 'bg-[var(--accent-primary,#4572e3)] text-white' : 'bg-[var(--bg-secondary)] text-[var(--text-muted)] hover:bg-[var(--bg-hover,#2a2a3e)]'}"
        >
          Classic
        </button>
        <button
          onclick={() => skinVariant = "slim"}
          class="px-[10px] py-[6px] rounded-lg text-[13px] font-semibold tracking-[0.01em] whitespace-nowrap box-border transition-colors cursor-pointer shrink-0 {skinVariant === 'slim' ? 'bg-[var(--accent-primary,#4572e3)] text-white' : 'bg-[var(--bg-secondary)] text-[var(--text-muted)] hover:bg-[var(--bg-hover,#2a2a3e)]'}"
        >
          Slim
        </button>

        {#if loadingCapes || capes.length > 0}
          <!-- CapeBar -->
          {#if loadingCapes}
            <div style="display: flex; align-items: center; gap: 4px;">
              <Loader2 size={14} style="animation: spin 1s linear infinite; color: var(--text-muted);" />
              <span style="font-size: 11px; color: var(--text-muted);">Capes…</span>
            </div>
          {:else if capes.length === 0}
            <span style="font-size: 11px; color: var(--text-muted);">No capes</span>
          {:else}
            <div style="display: flex; align-items: center; gap: 3px;">
              {#each capes as cape (cape.id)}
                {@const isActive = activeCape === cape.id}
                <div role="presentation" class="group relative inline-flex">
                  <div
                    role="button"
                    tabindex="0"
                    onclick={() => isActive ? handleCapeRemove() : handleCapeSelect(cape.id)}
                    onkeydown={(e) => { if (e.key === 'Enter') isActive ? handleCapeRemove() : handleCapeSelect(cape.id) }}
                    class="cursor-pointer shrink-0 leading-none"
                  >
                    <div class="w-[26px] h-[38px] rounded border-2 border-transparent group-hover:border-[var(--text-muted)] overflow-hidden bg-[var(--bg-secondary)] transition-colors relative flex items-center justify-center">
                      <div style="width: {CAPE_FRONT.w * CAPE_THUMB_SCALE}px; height: {CAPE_FRONT.h * CAPE_THUMB_SCALE}px; overflow: hidden; flex-shrink: 0;">
                        <img
                          src={cape.url}
                          alt={cape.alias}
                          draggable={false}
                          style="width: {CAPE_TEX_W * CAPE_THUMB_SCALE}px; max-width: none; height: auto; margin-left: {-CAPE_FRONT.x * CAPE_THUMB_SCALE}px; margin-top: {-CAPE_FRONT.y * CAPE_THUMB_SCALE}px; image-rendering: pixelated; display: block;"
                          onerror={(e) => { const img = e.currentTarget as HTMLImageElement; img.onerror = null; img.src = '/logo.png' }}
                        />
                      </div>
                      {#if isActive}
                        <div class="absolute inset-0 flex items-center justify-center bg-black/45">
                          <svg width="16" height="16" viewBox="0 0 12 12" fill="none">
                            <path d="M2 6L5 9L10 3" stroke="#22c55e" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round" class="group-hover:stroke-[#ef4444]" />
                          </svg>
                        </div>
                      {/if}
                    </div>
                  </div>
                  {@render tip(cape.alias)}
                </div>
              {/each}
            </div>
          {/if}

          {#if activeCapeUrl}
            <div role="presentation" class="group relative inline-flex">
              <button
                onclick={() => showElytra = !showElytra}
                class="flex items-center justify-center w-[34px] h-[34px] rounded-md bg-transparent hover:bg-[var(--bg-hover)] text-[var(--text-muted)] transition-colors cursor-pointer shrink-0"
              >
                {#if showElytra}
                  <RectangleVertical size={20} strokeWidth={2.5} />
                {:else}
                  <Plane size={20} strokeWidth={2.5} />
                {/if}
              </button>
              {@render tip(showElytra ? "Show as cape" : "Show as elytra")}
            </div>
          {/if}
        {/if}

        {#if hasPendingChanges}
          <div class="flex gap-2 ml-auto shrink-0">
            <button
              onclick={handleDiscard}
              disabled={saving}
              class="px-4 py-1.5 rounded-lg bg-[var(--bg-secondary,#1a1a2e)] text-[var(--text-muted,#888)] text-[13px] font-semibold transition-colors shrink-0 enabled:hover:bg-[var(--bg-hover,#2a2a3e)] enabled:cursor-pointer disabled:cursor-not-allowed disabled:opacity-50"
            >
              Cancel
            </button>
            <button
              onclick={handleSave}
              disabled={saving}
              class="px-4 py-1.5 rounded-lg bg-[#16a34a] enabled:hover:bg-[#15803d] text-white text-[13px] font-semibold transition-colors flex items-center gap-1.5 shrink-0 enabled:cursor-pointer disabled:cursor-not-allowed disabled:opacity-60"
            >
              {#if saving}
                Saving…
              {:else}
                <Save size={16} strokeWidth={2.5} /> Save
              {/if}
            </button>
          </div>
        {/if}
      </div>

      {#if recentSkins.length > 0}
        <div style="display: flex; align-items: center; gap: 4px; padding: 5px 6px; border-radius: 12px; background: var(--bg-elevated); backdrop-filter: blur(12px); flex-shrink: 0;">
          {#each recentSkins as skin}
            {@const match = skin.url.match(/texture\/([a-f0-9]+)/)}
            {@const hash = match ? match[1] : null}
            {@const bustUrl = hash ? `https://renders.stellarmc.gg/bust/${hash}${skin.variant === "slim" ? "?slim" : ""}` : skin.url}
            <div role="presentation" class="group relative inline-flex">
              <button
                onclick={() => handleRecentSkinSelect(skin)}
                disabled={uploading}
                class="box-border w-10 h-10 rounded-md p-0 border-2 border-transparent group-hover:border-[var(--text-muted)] overflow-hidden bg-transparent transition-colors shrink-0 enabled:cursor-pointer disabled:cursor-not-allowed disabled:opacity-40"
              >
                <img
                  src={bustUrl}
                  alt="Recent skin"
                  draggable={false}
                  class="w-full h-full object-cover block"
                  style="image-rendering: pixelated"
                />
              </button>
              {@render tip("Apply recent skin")}
            </div>
          {/each}
        </div>
      {/if}
    </div>
  </div>
{/if}
