// src/frontend/tabs/ModsTab.tsx
import { useState, useEffect, useRef } from "react"
import { invoke } from "@tauri-apps/api/core"
import { Search, Download, Loader2, Package, ChevronDown } from "lucide-react"
import type { Instance, ModrinthSearchResult, ModrinthProject, ModrinthVersion } from "../../types"

interface ModFile {
  filename: string
  size: number
}

interface ModsTabProps {
  selectedInstance: Instance | null
  instances: Instance[]
  onSetSelectedInstance: (instance: Instance) => void
}

export function ModsTab({ selectedInstance, instances, onSetSelectedInstance }: ModsTabProps) {
  const [searchQuery, setSearchQuery] = useState("")
  const [searchResults, setSearchResults] = useState<ModrinthSearchResult | null>(null)
  const [isSearching, setIsSearching] = useState(false)
  const [selectedMod, setSelectedMod] = useState<ModrinthProject | null>(null)
  const [modVersions, setModVersions] = useState<ModrinthVersion[]>([])
  const [isLoadingVersions, setIsLoadingVersions] = useState(false)
  const [downloadingMods, setDownloadingMods] = useState<Set<string>>(new Set())
  const [installedModFiles, setInstalledModFiles] = useState<Set<string>>(new Set())
  const searchTimeoutRef = useRef<NodeJS.Timeout | null>(null)
  const [showInstanceSelector, setShowInstanceSelector] = useState(false)
  const instanceSelectorRef = useRef<HTMLDivElement>(null)
  const [instanceIcons, setInstanceIcons] = useState<Record<string, string | null>>({})

  useEffect(() => {
    loadPopularMods()
  }, [])

  // Auto-select first Fabric instance if current selection is not Fabric
  useEffect(() => {
    if (!selectedInstance || selectedInstance.loader !== "fabric") {
      const fabricInstances = instances.filter(instance => instance.loader === "fabric")
      if (fabricInstances.length > 0) {
        onSetSelectedInstance(fabricInstances[0])
      }
    }
  }, [instances, selectedInstance])

  // Load installed mods whenever the selected instance changes
  useEffect(() => {
    if (selectedInstance && selectedInstance.loader === "fabric") {
      loadInstalledMods()
    }
  }, [selectedInstance])

  // Load icons for all instances
  useEffect(() => {
    const loadIcons = async () => {
      const icons: Record<string, string | null> = {}
      for (const instance of instances) {
        try {
          const icon = await invoke<string | null>("get_instance_icon", {
            instanceName: instance.name
          })
          icons[instance.name] = icon
        } catch (error) {
          console.error(`Failed to load icon for ${instance.name}:`, error)
          icons[instance.name] = null
        }
      }
      setInstanceIcons(icons)
    }

    if (instances.length > 0) {
      loadIcons()
    }
  }, [instances])

  useEffect(() => {
    const handleClickOutside = (event: MouseEvent) => {
      if (instanceSelectorRef.current && !instanceSelectorRef.current.contains(event.target as Node)) {
        setShowInstanceSelector(false)
      }
    }

    if (showInstanceSelector) {
      document.addEventListener('mousedown', handleClickOutside)
    }

    return () => {
      document.removeEventListener('mousedown', handleClickOutside)
    }
  }, [showInstanceSelector])

  useEffect(() => {
    if (searchTimeoutRef.current) {
      clearTimeout(searchTimeoutRef.current)
    }
    searchTimeoutRef.current = setTimeout(() => {
      handleSearch()
    }, 500)
    return () => {
      if (searchTimeoutRef.current) {
        clearTimeout(searchTimeoutRef.current)
      }
    }
  }, [searchQuery])

  const loadInstalledMods = async () => {
    if (!selectedInstance) return
    
    try {
      const mods = await invoke<ModFile[]>("get_installed_mods", {
        instanceName: selectedInstance.name,
      })
      
      // Create a set of installed filenames for quick lookup
      const filenames = new Set(mods.map(mod => mod.filename))
      setInstalledModFiles(filenames)
    } catch (error) {
      console.error("Failed to load installed mods:", error)
    }
  }

  const loadPopularMods = async () => {
    setIsSearching(true)
    try {
      const facets = JSON.stringify([["project_type:mod"]])
      const result = await invoke<ModrinthSearchResult>("search_mods", {
        query: "",
        facets,
        index: "downloads",
        offset: 0,
        limit: 25,
      })
      setSearchResults(result)
    } catch (error) {
      console.error("Failed to load popular mods:", error)
    } finally {
      setIsSearching(false)
    }
  }

  const handleSearch = async () => {
    const query = searchQuery.trim()
    setIsSearching(true)
    try {
      const facets = JSON.stringify([["project_type:mod"]])
      const result = await invoke<ModrinthSearchResult>("search_mods", {
        query: query || "",
        facets,
        index: query ? "relevance" : "downloads",
        offset: 0,
        limit: 20,
      })
      setSearchResults(result)
      setSelectedMod(null)
    } catch (error) {
      console.error("Search error:", error)
    } finally {
      setIsSearching(false)
    }
  }

  const getMinecraftVersion = (instance: Instance): string => {
    if (instance.loader === "fabric") {
      const parts = instance.version.split('-')
      return parts[parts.length - 1]
    }
    return instance.version
  }

  const handleModSelect = async (mod: ModrinthProject) => {
    if (!selectedInstance || selectedInstance.loader !== "fabric") return
    
    setSelectedMod(mod)
    setIsLoadingVersions(true)
    try {
      const mcVersion = getMinecraftVersion(selectedInstance)
      const loaders = [selectedInstance.loader]
      
      const versions = await invoke<ModrinthVersion[]>("get_mod_versions", {
        idOrSlug: mod.project_id,
        loaders: loaders,
        gameVersions: [mcVersion],
      })
      setModVersions(versions)
    } catch (error) {
      console.error("Failed to load versions:", error)
    } finally {
      setIsLoadingVersions(false)
    }
  }

  const isModInstalled = (version: ModrinthVersion): boolean => {
    // Check if any of the version's files are installed
    return version.files.some(file => installedModFiles.has(file.filename))
  }

  const handleDownloadMod = async (version: ModrinthVersion) => {
    if (!selectedInstance || selectedInstance.loader !== "fabric") return

    const primaryFile = version.files.find(f => f.primary) || version.files[0]
    if (!primaryFile) return

    setDownloadingMods(prev => new Set(prev).add(version.id))
    
    try {
      await invoke<string>("download_mod", {
        instanceName: selectedInstance.name,
        downloadUrl: primaryFile.url,
        filename: primaryFile.filename,
      })
      
      // Add the filename to installed mods
      setInstalledModFiles(prev => new Set(prev).add(primaryFile.filename))
    } catch (error) {
      console.error("Download error:", error)
    } finally {
      setDownloadingMods(prev => {
        const newSet = new Set(prev)
        newSet.delete(version.id)
        return newSet
      })
    }
  }

  const formatDownloads = (downloads: number): string => {
    if (downloads >= 1000000) return `${(downloads / 1000000).toFixed(1)}M`
    if (downloads >= 1000) return `${(downloads / 1000).toFixed(1)}K`
    return downloads.toString()
  }

  return (
    <div className="p-6 space-y-4">
      <div className="max-w-7xl mx-auto">
        <div className="flex items-center justify-between mb-4">
          <div>
            <h1 className="text-2xl font-semibold text-[#e8e8e8] tracking-tight">Mods</h1>
            <p className="text-sm text-[#808080] mt-0.5">Browse and install mods from Modrinth</p>
          </div>
          {selectedInstance && selectedInstance.loader === "fabric" && (
            <div className="relative" ref={instanceSelectorRef}>
              <button
                onClick={() => setShowInstanceSelector(!showInstanceSelector)}
                className="flex items-center gap-2 px-3 py-2 bg-[#1a1a1a] hover:bg-[#1f1f1f] border border-[#2a2a2a] rounded-lg text-sm transition-colors cursor-pointer"
              >
                {instanceIcons[selectedInstance.name] ? (
                  <img
                    src={instanceIcons[selectedInstance.name]!}
                    alt={selectedInstance.name}
                    className="w-7 h-7 rounded-lg object-cover flex-shrink-0"
                  />
                ) : (
                  <div className="w-7 h-7 flex items-center justify-center flex-shrink-0">
                    <Package size={20} className="text-[#4a4a4a]" strokeWidth={1.5} />
                  </div>
                )}
                <div className="text-left min-w-0">
                  <div className="font-semibold text-[#e8e8e8] whitespace-nowrap leading-tight">{selectedInstance.name}</div>
                  <div className="flex items-center gap-1 text-xs leading-tight mt-0.5">
                    <span className="text-[#808080]">{getMinecraftVersion(selectedInstance)}</span>
                    <span className="text-[#4a4a4a]">•</span>
                    <span className="text-[#3b82f6]">Fabric</span>
                  </div>
                </div>
                <ChevronDown size={16} className={`text-[#808080] ml-auto transition-transform ${showInstanceSelector ? 'rotate-180' : ''}`} strokeWidth={2} />
              </button>
              {showInstanceSelector && (
                <div className="absolute top-full mt-1 right-0 bg-[#1a1a1a] border border-[#2a2a2a] rounded-lg overflow-hidden z-10 min-w-[240px] max-h-[400px] overflow-y-auto">
                  {instances.filter(instance => instance.loader === "fabric").length === 0 ? (
                    <div className="px-3 py-4 text-center">
                      <p className="text-sm text-[#808080] mb-1">No Fabric instances</p>
                      <p className="text-xs text-[#4a4a4a]">Create a Fabric instance to install mods</p>
                    </div>
                  ) : (
                    instances
                      .filter(instance => instance.loader === "fabric")
                      .map((instance) => {
                        const icon = instanceIcons[instance.name]
                        return (
                          <button
                            key={instance.name}
                            onClick={() => {
                              onSetSelectedInstance(instance)
                              setShowInstanceSelector(false)
                            }}
                            className={`w-full flex items-center gap-3 px-3 py-2.5 text-left text-sm cursor-pointer transition-colors ${
                              selectedInstance.name === instance.name
                                ? "bg-[#3b82f6]/10 text-[#e8e8e8]"
                                : "text-[#808080] hover:bg-[#0d0d0d]"
                            }`}
                          >
                            {icon ? (
                              <img
                                src={icon}
                                alt={instance.name}
                                className="w-8 h-8 rounded-lg object-cover flex-shrink-0"
                              />
                            ) : (
                              <div className="w-8 h-8 flex items-center justify-center flex-shrink-0">
                                <Package size={24} className="text-[#4a4a4a]" strokeWidth={1.5} />
                              </div>
                            )}
                            <div className="flex-1 min-w-0">
                              <div className="font-semibold text-[#e8e8e8] truncate">{instance.name}</div>
                              <div className="flex items-center gap-1 text-xs">
                                <span>{getMinecraftVersion(instance)}</span>
                                <span>•</span>
                                <span className="text-[#3b82f6]">Fabric</span>
                              </div>
                            </div>
                          </button>
                        )
                      })
                  )}
                </div>
              )}
            </div>
          )}
        </div>

        <div className="relative mb-4">
          <Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-[#4a4a4a]" strokeWidth={2} />
          <input
            type="text"
            placeholder="Search mods..."
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            className="w-full bg-[#1a1a1a] border border-[#2a2a2a] rounded-lg pl-10 pr-4 py-2.5 text-sm text-[#e8e8e8] placeholder-[#4a4a4a] focus:outline-none focus:border-[#16a34a] transition-colors"
          />
          {isSearching && (
            <div className="absolute right-3 top-1/2 -translate-y-1/2">
              <Loader2 size={16} className="animate-spin text-[#16a34a]" />
            </div>
          )}
        </div>

        {searchResults && (
          <div className="grid grid-cols-1 lg:grid-cols-3 gap-4">
            <div className="lg:col-span-2 space-y-3">
              {searchResults.hits.map((mod) => (
                <div
                  key={mod.project_id}
                  onClick={() => handleModSelect(mod)}
                  className={`bg-[#1a1a1a] hover:bg-[#1f1f1f] border rounded-xl p-4 cursor-pointer transition-all ${
                    selectedMod?.project_id === mod.project_id ? "border-[#16a34a]" : "border-[#2a2a2a]"
                  }`}
                >
                  <div className="flex gap-4">
                    {mod.icon_url ? (
                      <img src={mod.icon_url} alt={mod.title} className="w-16 h-16 rounded-lg flex-shrink-0 border border-[#2a2a2a]" />
                    ) : (
                      <div className="w-16 h-16 bg-gradient-to-br from-[#16a34a]/10 to-[#15803d]/10 rounded-lg flex items-center justify-center flex-shrink-0 border border-[#16a34a]/20">
                        <Package size={24} className="text-[#16a34a]/60" strokeWidth={1.5} />
                      </div>
                    )}
                    <div className="flex-1 min-w-0">
                      <div className="flex items-start justify-between gap-2 mb-0">
                        <h3 className="font-semibold text-base text-[#e8e8e8] truncate">{mod.title}</h3>
                        <span className="text-xs text-[#808080] whitespace-nowrap">by {mod.author}</span>
                      </div>
                      <p className="text-sm text-[#808080] line-clamp-2 mb-2">{mod.description}</p>
                      <div className="flex items-center gap-3 text-xs text-[#4a4a4a]">
                        <span className="flex items-center gap-1">
                          <Download size={12} />
                          {formatDownloads(mod.downloads)}
                        </span>
                        <span>•</span>
                        <span className="truncate">{mod.categories.slice(0, 2).join(', ')}</span>
                      </div>
                    </div>
                  </div>
                </div>
              ))}
            </div>

            {selectedMod && (
              <div className="bg-[#1a1a1a] border border-[#2a2a2a] rounded-xl p-5 sticky top-4 self-start">
                <div className="flex gap-3 mb-4">
                  {selectedMod.icon_url && (
                    <img src={selectedMod.icon_url} alt={selectedMod.title} className="w-16 h-16 rounded-lg border border-[#2a2a2a]" />
                  )}
                  <div className="flex-1 min-w-0">
                    <h2 className="text-xl font-semibold text-[#e8e8e8] truncate">{selectedMod.title}</h2>
                    <p className="text-sm text-[#808080]">by {selectedMod.author}</p>
                  </div>
                </div>
                
                <p className="text-sm text-[#808080] mb-4 leading-relaxed">{selectedMod.description}</p>
                
                <div className="flex gap-4 mb-5 text-xs text-[#4a4a4a]">
                  <span className="flex items-center gap-1">
                    <Download size={12} />
                    {formatDownloads(selectedMod.downloads)}
                  </span>
                  <span>{selectedMod.follows.toLocaleString()} followers</span>
                </div>

                <div className="border-t border-[#2a2a2a] pt-4">
                  <h3 className="font-semibold text-sm text-[#e8e8e8] mb-3">Versions</h3>
                  {isLoadingVersions ? (
                    <div className="text-center py-6">
                      <Loader2 size={20} className="animate-spin text-[#16a34a] mx-auto" />
                    </div>
                  ) : modVersions.length === 0 ? (
                    <p className="text-sm text-[#4a4a4a] text-center py-3">No compatible versions</p>
                  ) : (
                    <div className="space-y-2 max-h-96 overflow-y-auto">
                      {modVersions.map((version) => {
                        const installed = isModInstalled(version)
                        const downloading = downloadingMods.has(version.id)
                        
                        return (
                          <div
                            key={version.id}
                            className="bg-[#0d0d0d] border border-[#2a2a2a] rounded-lg p-3 flex items-center justify-between gap-2"
                          >
                            <div className="flex-1 min-w-0">
                              <div className="text-sm font-medium text-[#e8e8e8] truncate">{version.name}</div>
                              <div className="text-xs text-[#4a4a4a] truncate mt-0.5">
                                {version.loaders.join(', ')} • {version.game_versions[0]}
                              </div>
                            </div>
                            <button
                              onClick={() => handleDownloadMod(version)}
                              disabled={!selectedInstance || downloading || installed}
                              className="px-3 py-2 bg-[#16a34a] hover:bg-[#15803d] disabled:opacity-50 disabled:cursor-not-allowed text-white rounded-md text-xs font-medium whitespace-nowrap transition-all shadow-sm cursor-pointer"
                            >
                              {downloading ? (
                                <Loader2 size={14} className="animate-spin" />
                              ) : installed ? (
                                "Installed"
                              ) : (
                                "Install"
                              )}
                            </button>
                          </div>
                        )
                      })}
                    </div>
                  )}
                </div>
              </div>
            )}
          </div>
        )}
      </div>
    </div>
  )
}

// frontend/features/modrinth/ModsTab.svelte
<script lang="ts">
  import { Search, Download, Loader2, Package } from "lucide-svelte"
  import { invoke } from "@tauri-apps/api/core"
  import { untrack } from "svelte"
  import type { Snippet } from "svelte"
  import type { Instance, ModrinthSearchResult, ModrinthProject, ModrinthVersion, ModFile } from "../../types"
  import { formatDownloads } from "../../lib/format"
  import { getMinecraftVersion } from "../../lib/version"

  let {
    selectedInstance = null,
    instances = [],
    onSetSelectedInstance = (_: Instance) => {},
    sourceSelector,
    modsSelector,
    hideToolbar = false,
    searchQuery = undefined as string | undefined,
    onSearchQueryChange = undefined as ((query: string) => void) | undefined,
  }: {
    selectedInstance: Instance | null
    instances: Instance[]
    onSetSelectedInstance: (instance: Instance) => void
    sourceSelector?: Snippet
    modsSelector?: Snippet
    hideToolbar?: boolean
    searchQuery?: string
    onSearchQueryChange?: (query: string) => void
  } = $props()

  let internalSearchQuery = $state("")
  let debounceSearchQuery = $derived(searchQuery ?? internalSearchQuery)
  let hits = $state<ModrinthProject[]>([])
  let isSearching = $state(false)
  let isLoadingMore = $state(false)
  let selectedMod = $state<ModrinthProject | null>(null)
  let modVersions = $state<ModrinthVersion[]>([])
  let isLoadingVersions = $state(false)
  let downloadingMods = $state<Set<string>>(new Set())
  let installedModFiles = $state<Set<string>>(new Set())
  let sentinelEl: HTMLDivElement | undefined = $state()
  let searchTimeout: ReturnType<typeof setTimeout> | undefined
  let offset = 0
  let hasMore = true
  const itemsPerPage = 20

  $effect(() => {
    if (!selectedInstance || (selectedInstance.loader !== "fabric" && selectedInstance.loader !== "neoforge" && selectedInstance.loader !== "forge")) {
      const moddedInstances = instances.filter(i => i.loader === "fabric" || i.loader === "neoforge" || i.loader === "forge")
      if (moddedInstances.length > 0) onSetSelectedInstance(moddedInstances[0])
    }
  })

  $effect(() => {
    if (selectedInstance && (selectedInstance.loader === "fabric" || selectedInstance.loader === "neoforge" || selectedInstance.loader === "forge")) {
      loadInstalledMods()
    }
  })

  $effect(() => {
    debounceSearchQuery;
    if (searchTimeout) clearTimeout(searchTimeout)
    offset = 0
    hasMore = true
    searchTimeout = setTimeout(() => {
      fetchMods(0, true)
    }, untrack(() => hits.length === 0 ? 0 : 300))
    return () => clearTimeout(searchTimeout)
  })

  $effect(() => {
    if (!sentinelEl) return
    const el = sentinelEl
    const observer = new IntersectionObserver(
      (entries) => {
        if (entries[0].isIntersecting && !isLoadingMore && !isSearching && hasMore) {
          loadMore()
        }
      },
      { threshold: 0.1 }
    )
    observer.observe(el)
    return () => observer.disconnect()
  })

  async function fetchMods(offsetVal: number, replace: boolean) {
    const query = debounceSearchQuery.trim()
    if (replace) isSearching = true
    else isLoadingMore = true
    try {
      const result = await invoke<ModrinthSearchResult>("search_mods", {
        query: query || "",
        facets: JSON.stringify([["project_type:mod"]]),
        index: query ? "relevance" : "downloads",
        offset: offsetVal,
        limit: itemsPerPage,
      })
      offset = offsetVal + result.hits.length
      hasMore = offsetVal + result.hits.length < result.total_hits
      if (replace) {
        hits = result.hits
      } else {
        const ids = new Set(hits.map(h => h.project_id))
        hits = [...hits, ...result.hits.filter(h => !ids.has(h.project_id))]
      }
    } catch (error) {
      console.error("Search error:", error)
    } finally {
      if (replace) isSearching = false
      else isLoadingMore = false
    }
  }

  function loadMore() {
    if (!hasMore || isLoadingMore || isSearching) return
    fetchMods(offset, false)
  }

  async function loadInstalledMods() {
    if (!selectedInstance) return
    try {
      const mods = await invoke<ModFile[]>("get_installed_mods", { instanceName: selectedInstance.name })
      installedModFiles = new Set(mods.map(mod => mod.filename))
    } catch (error) {
      console.error("Failed to load installed mods:", error)
    }
  }

  async function handleModSelect(mod: ModrinthProject) {
    if (!selectedInstance || (selectedInstance.loader !== "fabric" && selectedInstance.loader !== "neoforge" && selectedInstance.loader !== "forge")) return
    selectedMod = mod
    isLoadingVersions = true
    try {
      const versions = await invoke<ModrinthVersion[]>("get_mod_versions", {
        idOrSlug: mod.project_id,
        loaders: [selectedInstance.loader],
        gameVersions: [getMinecraftVersion(selectedInstance)],
      })
      modVersions = versions
    } catch (error) {
      console.error("Failed to load versions:", error)
    } finally {
      isLoadingVersions = false
    }
  }

  function isModInstalled(version: ModrinthVersion): boolean {
    return version.files.some(file => installedModFiles.has(file.filename))
  }

  async function handleDownloadMod(version: ModrinthVersion) {
    if (!selectedInstance || (selectedInstance.loader !== "fabric" && selectedInstance.loader !== "neoforge" && selectedInstance.loader !== "forge")) return
    const primaryFile = version.files.find(f => f.primary) || version.files[0]
    if (!primaryFile) return
    downloadingMods = new Set(downloadingMods).add(version.id)
    try {
      await invoke<string>("download_mod", {
        instanceName: selectedInstance.name, downloadUrl: primaryFile.url, filename: primaryFile.filename,
      })
      installedModFiles = new Set(installedModFiles).add(primaryFile.filename)
    } catch (error) {
      console.error("Download error:", error)
    } finally {
      const n = new Set(downloadingMods)
      n.delete(version.id)
      downloadingMods = n
    }
  }

</script>

<div class="max-w-7xl mx-auto h-full flex flex-col">
  {#if !hideToolbar}
    <div class="sticky top-0 z-10 bg-[var(--content-bg)] pb-4 flex-shrink-0">
      <div class="flex gap-2 items-stretch">
        {#if sourceSelector}
          {@render sourceSelector()}
        {/if}
        <div class="relative flex-1 rounded-md bg-[var(--bg-tertiary)]">
          <Search size={16} class="absolute left-3 top-1/2 -translate-y-1/2 text-[var(--text-muted)] z-20 pointer-events-none" strokeWidth={2} />
          <input
            type="text"
            placeholder="Search mods..."
            value={searchQuery ?? internalSearchQuery}
            oninput={(e) => onSearchQueryChange ? onSearchQueryChange((e.target as HTMLInputElement).value) : (internalSearchQuery = (e.target as HTMLInputElement).value)}
            class="w-full bg-transparent rounded-md pl-10 pr-4 py-2.5 text-sm text-[var(--text-primary)] placeholder-[var(--text-muted)] focus:outline-none transition-all relative z-10"
          />
          {#if isSearching}
            <div class="absolute right-3 top-1/2 -translate-y-1/2 z-20">
              <Loader2 size={16} class="animate-spin text-[#16a34a]" />
            </div>
          {/if}
        </div>
        {#if modsSelector}
          {@render modsSelector()}
        {/if}
      </div>
    </div>
  {/if}

  <div class="flex-1 min-h-0 grid grid-cols-1 lg:grid-cols-3 gap-2">
    <div class="lg:col-span-2 space-y-3 overflow-y-auto pr-2">
      {#each hits as mod (mod.project_id)}
        <div
          class="rounded-md overflow-hidden cursor-pointer transition-all {selectedMod?.project_id === mod.project_id ? 'bg-[var(--bg-elevated)]' : 'bg-[var(--bg-tertiary)]'}"
          role="button"
          tabindex="0"
          onkeydown={(e) => { if (e.key === 'Enter') handleModSelect(mod); }}
          onclick={() => handleModSelect(mod)}
        >
          <div class="flex min-h-0 relative z-0">
            {#if mod.icon_url}
              <div class="w-24 h-24 flex items-center justify-center flex-shrink-0 rounded m-2">
                <img src={mod.icon_url} alt={mod.title} class="w-full h-full object-contain rounded" />
              </div>
            {:else}
              <div class="w-24 h-24 bg-gradient-to-br from-[#16a34a]/10 to-[#22c55e]/10 flex items-center justify-center flex-shrink-0 rounded m-2">
                <Package size={48} class="text-[#16a34a]" />
              </div>
            {/if}
            <div class="flex-1 min-w-0 py-2 px-3 flex items-center gap-3">
              <div class="flex-1 min-w-0">
                <div class="flex items-start justify-between gap-2 mb-0">
                  <h3 class="font-semibold text-base text-[var(--text-primary)] truncate">{mod.title}</h3>
                  <span class="text-xs text-[var(--text-muted)] whitespace-nowrap">by {mod.author}</span>
                </div>
                <p class="text-sm text-[var(--text-muted)] line-clamp-2 mb-2">{mod.description}</p>
                <div class="flex items-center gap-2 text-xs flex-wrap">
                  <span class="flex items-center gap-1 bg-[var(--bg-secondary)] px-2 py-1 rounded text-[var(--text-muted)]">
                    <Download size={12} />
                    {formatDownloads(mod.downloads)}
                  </span>
                  {#each mod.categories.slice(0, 2) as category}
                    <span class="bg-[var(--bg-secondary)] px-2 py-1 rounded text-[var(--text-muted)]">{category}</span>
                  {/each}
                </div>
              </div>
            </div>
          </div>
        </div>
      {/each}

      <div bind:this={sentinelEl} class="flex items-center justify-center py-4">
        {#if isLoadingMore}
          <Loader2 size={20} class="animate-spin text-[#16a34a]" />
        {/if}
      </div>
    </div>

    {#if selectedMod}
      <div class="bg-[var(--bg-tertiary)] rounded-md p-3 sticky top-0 self-start">
        <div class="flex gap-3 mb-4">
          {#if selectedMod.icon_url}
            <img src={selectedMod.icon_url} alt={selectedMod.title} class="w-16 h-16 rounded" />
          {/if}
          <div class="flex-1 min-w-0">
            <h2 class="text-xl font-semibold text-[var(--text-primary)] truncate">{selectedMod.title}</h2>
            <p class="text-sm text-[var(--text-muted)]">by {selectedMod.author}</p>
          </div>
        </div>
        <p class="text-sm text-[var(--text-muted)] mb-4 leading-relaxed">{selectedMod.description}</p>
        <div class="flex gap-2 mb-5 text-xs flex-wrap">
          <span class="flex items-center gap-1 bg-[var(--bg-secondary)] px-2 py-1 rounded text-[var(--text-muted)]">
            <Download size={12} />
            {formatDownloads(selectedMod.downloads)}
          </span>
          <span class="bg-[var(--bg-secondary)] px-2 py-1 rounded text-[var(--text-muted)]">{selectedMod.follows.toLocaleString()} followers</span>
        </div>
        <div class="pt-1">
          <h3 class="font-semibold text-sm text-[var(--text-primary)] mb-3">Versions</h3>
          {#if isLoadingVersions}
            <div class="text-center py-6"><Loader2 size={20} class="animate-spin text-[#16a34a] mx-auto" /></div>
          {:else if modVersions.length === 0}
            <p class="text-sm text-[#3a3f4b] text-center py-3">No compatible versions</p>
          {:else}
            <div class="space-y-2 max-h-[40vh] overflow-y-auto pr-1.5">
              {#each modVersions as version (version.id)}
                {@const installed = isModInstalled(version)}
                {@const downloading = downloadingMods.has(version.id)}
                <div class="bg-[var(--bg-secondary)] rounded p-3 flex items-center justify-between gap-2">
                  <div class="flex-1 min-w-0">
                    <div class="text-sm font-medium text-[var(--text-primary)] truncate">{version.name}</div>
                    <div class="text-xs text-[#3a3f4b] truncate mt-0.5">
                      {version.loaders.join(', ')} • {selectedInstance ? getMinecraftVersion(selectedInstance) : version.game_versions[0]}
                    </div>
                  </div>
                  <button
                    onclick={() => handleDownloadMod(version)}
                    disabled={!selectedInstance || downloading || installed}
                    class="px-3 py-2 bg-[#16a34a] hover:bg-[#22c55e] disabled:opacity-50 disabled:cursor-not-allowed text-white rounded text-xs font-medium whitespace-nowrap transition-all cursor-pointer flex items-center gap-1"
                  >
                    {#if downloading}
                      <Loader2 size={14} class="animate-spin" />
                    {:else if installed}
                      Installed
                    {:else}
                      <Download size={14} />Install
                    {/if}
                  </button>
                </div>
              {/each}
            </div>
          {/if}
        </div>
      </div>
    {/if}
  </div>
</div>
